# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_AssignLevelsToBuildings.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AssignLevelsToBuildings_window(object):
    def setupUi(self, AssignLevelsToBuildings_window):
        AssignLevelsToBuildings_window.setObjectName("AssignLevelsToBuildings_window")
        AssignLevelsToBuildings_window.setEnabled(True)
        AssignLevelsToBuildings_window.resize(713, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AssignLevelsToBuildings_window.sizePolicy().hasHeightForWidth())
        AssignLevelsToBuildings_window.setSizePolicy(sizePolicy)
        AssignLevelsToBuildings_window.setMinimumSize(QtCore.QSize(713, 300))
        AssignLevelsToBuildings_window.setMaximumSize(QtCore.QSize(713, 300))
        AssignLevelsToBuildings_window.setSizeIncrement(QtCore.QSize(0, 0))
        AssignLevelsToBuildings_window.setLocale(QtCore.QLocale(QtCore.QLocale.Italian, QtCore.QLocale.Italy))
        self.verticalLayoutWidget = QtWidgets.QWidget(AssignLevelsToBuildings_window)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 170, 691, 61))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.buildings_layer_verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.buildings_layer_verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.buildings_layer_verticalLayout.setObjectName("buildings_layer_verticalLayout")
        self.buildings_layer_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buildings_layer_label.sizePolicy().hasHeightForWidth())
        self.buildings_layer_label.setSizePolicy(sizePolicy)
        self.buildings_layer_label.setObjectName("buildings_layer_label")
        self.buildings_layer_verticalLayout.addWidget(self.buildings_layer_label)
        self.buildings_layer_comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.buildings_layer_comboBox.setObjectName("buildings_layer_comboBox")
        self.buildings_layer_verticalLayout.addWidget(self.buildings_layer_comboBox)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(AssignLevelsToBuildings_window)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 240, 691, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.progressBar = QtWidgets.QProgressBar(self.horizontalLayoutWidget_2)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout.addWidget(self.progressBar)
        self.run_buttonBox = QtWidgets.QDialogButtonBox(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.run_buttonBox.sizePolicy().hasHeightForWidth())
        self.run_buttonBox.setSizePolicy(sizePolicy)
        self.run_buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.run_buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.run_buttonBox.setObjectName("run_buttonBox")
        self.horizontalLayout.addWidget(self.run_buttonBox)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(AssignLevelsToBuildings_window)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 691, 61))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.receivers_layer_verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.receivers_layer_verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.receivers_layer_verticalLayout.setObjectName("receivers_layer_verticalLayout")
        self.receiver_points_layer_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.receiver_points_layer_label.sizePolicy().hasHeightForWidth())
        self.receiver_points_layer_label.setSizePolicy(sizePolicy)
        self.receiver_points_layer_label.setObjectName("receiver_points_layer_label")
        self.receivers_layer_verticalLayout.addWidget(self.receiver_points_layer_label)
        self.receiver_points_layer_comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.receiver_points_layer_comboBox.setObjectName("receiver_points_layer_comboBox")
        self.receivers_layer_verticalLayout.addWidget(self.receiver_points_layer_comboBox)
        self.line = QtWidgets.QFrame(AssignLevelsToBuildings_window)
        self.line.setGeometry(QtCore.QRect(10, 150, 681, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(AssignLevelsToBuildings_window)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 90, 691, 60))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.choose_fileds_label = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.choose_fileds_label.sizePolicy().hasHeightForWidth())
        self.choose_fileds_label.setSizePolicy(sizePolicy)
        self.choose_fileds_label.setObjectName("choose_fileds_label")
        self.verticalLayout.addWidget(self.choose_fileds_label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.level_1_comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.level_1_comboBox.sizePolicy().hasHeightForWidth())
        self.level_1_comboBox.setSizePolicy(sizePolicy)
        self.level_1_comboBox.setObjectName("level_1_comboBox")
        self.horizontalLayout_2.addWidget(self.level_1_comboBox)
        self.level_2_comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        self.level_2_comboBox.setObjectName("level_2_comboBox")
        self.horizontalLayout_2.addWidget(self.level_2_comboBox)
        self.level_3_comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        self.level_3_comboBox.setObjectName("level_3_comboBox")
        self.horizontalLayout_2.addWidget(self.level_3_comboBox)
        self.level_4_comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        self.level_4_comboBox.setObjectName("level_4_comboBox")
        self.horizontalLayout_2.addWidget(self.level_4_comboBox)
        self.level_5_comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        self.level_5_comboBox.setObjectName("level_5_comboBox")
        self.horizontalLayout_2.addWidget(self.level_5_comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(AssignLevelsToBuildings_window)
        self.run_buttonBox.accepted.connect(AssignLevelsToBuildings_window.accept)
        self.run_buttonBox.rejected.connect(AssignLevelsToBuildings_window.reject)
        QtCore.QMetaObject.connectSlotsByName(AssignLevelsToBuildings_window)

    def retranslateUi(self, AssignLevelsToBuildings_window):
        _translate = QtCore.QCoreApplication.translate
        AssignLevelsToBuildings_window.setWindowTitle(_translate("AssignLevelsToBuildings_window", "opeNoise - Assign Levels To Buildings"))
        self.buildings_layer_label.setText(_translate("AssignLevelsToBuildings_window", "Buildings layer (input polygon layer)"))
        self.receiver_points_layer_label.setText(_translate("AssignLevelsToBuildings_window", "Receiver points layer (input point layer)"))
        self.choose_fileds_label.setText(_translate("AssignLevelsToBuildings_window", "Choose the sound level fields to assign to the buildings layer (the max level):"))

