# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_ApplyNoiseSymbology.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ApplyNoiseSymbology_window(object):
    def setupUi(self, ApplyNoiseSymbology_window):
        ApplyNoiseSymbology_window.setObjectName("ApplyNoiseSymbology_window")
        ApplyNoiseSymbology_window.setEnabled(True)
        ApplyNoiseSymbology_window.resize(713, 225)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ApplyNoiseSymbology_window.sizePolicy().hasHeightForWidth())
        ApplyNoiseSymbology_window.setSizePolicy(sizePolicy)
        ApplyNoiseSymbology_window.setMinimumSize(QtCore.QSize(713, 225))
        ApplyNoiseSymbology_window.setMaximumSize(QtCore.QSize(713, 225))
        ApplyNoiseSymbology_window.setSizeIncrement(QtCore.QSize(0, 0))
        ApplyNoiseSymbology_window.setLocale(QtCore.QLocale(QtCore.QLocale.Italian, QtCore.QLocale.Italy))
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(ApplyNoiseSymbology_window)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 165, 691, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.progressBar = QtWidgets.QProgressBar(self.horizontalLayoutWidget_2)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout.addWidget(self.progressBar)
        self.run_buttonBox = QtWidgets.QDialogButtonBox(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.run_buttonBox.sizePolicy().hasHeightForWidth())
        self.run_buttonBox.setSizePolicy(sizePolicy)
        self.run_buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.run_buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.run_buttonBox.setObjectName("run_buttonBox")
        self.horizontalLayout.addWidget(self.run_buttonBox)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(ApplyNoiseSymbology_window)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 15, 691, 61))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.receivers_layer_verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.receivers_layer_verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.receivers_layer_verticalLayout.setObjectName("receivers_layer_verticalLayout")
        self.receiver_points_layer_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.receiver_points_layer_label.sizePolicy().hasHeightForWidth())
        self.receiver_points_layer_label.setSizePolicy(sizePolicy)
        self.receiver_points_layer_label.setObjectName("receiver_points_layer_label")
        self.receivers_layer_verticalLayout.addWidget(self.receiver_points_layer_label)
        self.layer_comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.layer_comboBox.setObjectName("layer_comboBox")
        self.receivers_layer_verticalLayout.addWidget(self.layer_comboBox)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(ApplyNoiseSymbology_window)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 90, 691, 71))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.choose_fileds_label = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.choose_fileds_label.sizePolicy().hasHeightForWidth())
        self.choose_fileds_label.setSizePolicy(sizePolicy)
        self.choose_fileds_label.setMinimumSize(QtCore.QSize(400, 0))
        self.choose_fileds_label.setMaximumSize(QtCore.QSize(400, 4007215))
        self.choose_fileds_label.setObjectName("choose_fileds_label")
        self.horizontalLayout_2.addWidget(self.choose_fileds_label)
        self.level_comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.level_comboBox.sizePolicy().hasHeightForWidth())
        self.level_comboBox.setSizePolicy(sizePolicy)
        self.level_comboBox.setObjectName("level_comboBox")
        self.horizontalLayout_2.addWidget(self.level_comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.choose_fileds_label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.choose_fileds_label_3.sizePolicy().hasHeightForWidth())
        self.choose_fileds_label_3.setSizePolicy(sizePolicy)
        self.choose_fileds_label_3.setObjectName("choose_fileds_label_3")
        self.verticalLayout.addWidget(self.choose_fileds_label_3)

        self.retranslateUi(ApplyNoiseSymbology_window)
        self.run_buttonBox.accepted.connect(ApplyNoiseSymbology_window.accept)
        self.run_buttonBox.rejected.connect(ApplyNoiseSymbology_window.reject)
        QtCore.QMetaObject.connectSlotsByName(ApplyNoiseSymbology_window)

    def retranslateUi(self, ApplyNoiseSymbology_window):
        _translate = QtCore.QCoreApplication.translate
        ApplyNoiseSymbology_window.setWindowTitle(_translate("ApplyNoiseSymbology_window", "opeNoise - Apply Noise Symbology"))
        self.receiver_points_layer_label.setText(_translate("ApplyNoiseSymbology_window", "Input layer:"))
        self.choose_fileds_label.setText(_translate("ApplyNoiseSymbology_window", "Choose the sound level fields to apply noise symbology:"))
        self.choose_fileds_label_3.setText(_translate("ApplyNoiseSymbology_window", "NOTE: For negative values the legend is \'No Level\'."))

