# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_CalculateNoiseLevels.ui'
#
# Created: Mon Nov 13 09:34:09 2017
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CalculateNoiseLevels_window(object):
    def setupUi(self, CalculateNoiseLevels_window):
        CalculateNoiseLevels_window.setObjectName(_fromUtf8("CalculateNoiseLevels_window"))
        CalculateNoiseLevels_window.resize(848, 611)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CalculateNoiseLevels_window.sizePolicy().hasHeightForWidth())
        CalculateNoiseLevels_window.setSizePolicy(sizePolicy)
        CalculateNoiseLevels_window.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        CalculateNoiseLevels_window.setModal(False)
        self.tabWidget = QtGui.QTabWidget(CalculateNoiseLevels_window)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 831, 591))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.label_8 = QtGui.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(40, 50, 471, 17))
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.reload_last_settings_pushButton = QtGui.QPushButton(self.tab)
        self.reload_last_settings_pushButton.setGeometry(QtCore.QRect(300, 270, 191, 31))
        self.reload_last_settings_pushButton.setObjectName(_fromUtf8("reload_last_settings_pushButton"))
        self.label_9 = QtGui.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(50, 220, 471, 17))
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.reload_saved_settings_pushButton = QtGui.QPushButton(self.tab)
        self.reload_saved_settings_pushButton.setGeometry(QtCore.QRect(300, 320, 191, 31))
        self.reload_saved_settings_pushButton.setObjectName(_fromUtf8("reload_saved_settings_pushButton"))
        self.label_10 = QtGui.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(40, 80, 471, 17))
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(100, 110, 471, 17))
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(100, 130, 661, 17))
        self.label_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(100, 150, 661, 17))
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tabGeometry = QtGui.QWidget()
        self.tabGeometry.setObjectName(_fromUtf8("tabGeometry"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.tabGeometry)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(60, 50, 481, 61))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.receivers_layer_verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.receivers_layer_verticalLayout.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.receivers_layer_verticalLayout.setMargin(0)
        self.receivers_layer_verticalLayout.setObjectName(_fromUtf8("receivers_layer_verticalLayout"))
        self.receivers_layer_label = QtGui.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.receivers_layer_label.sizePolicy().hasHeightForWidth())
        self.receivers_layer_label.setSizePolicy(sizePolicy)
        self.receivers_layer_label.setObjectName(_fromUtf8("receivers_layer_label"))
        self.receivers_layer_verticalLayout.addWidget(self.receivers_layer_label)
        self.receivers_layer_comboBox = QtGui.QComboBox(self.verticalLayoutWidget_2)
        self.receivers_layer_comboBox.setObjectName(_fromUtf8("receivers_layer_comboBox"))
        self.receivers_layer_verticalLayout.addWidget(self.receivers_layer_comboBox)
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.tabGeometry)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(60, 160, 481, 182))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.sources_layer_verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.sources_layer_verticalLayout.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.sources_layer_verticalLayout.setMargin(0)
        self.sources_layer_verticalLayout.setObjectName(_fromUtf8("sources_layer_verticalLayout"))
        self.sources_pts_layer_checkBox = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        self.sources_pts_layer_checkBox.setEnabled(True)
        self.sources_pts_layer_checkBox.setChecked(False)
        self.sources_pts_layer_checkBox.setObjectName(_fromUtf8("sources_pts_layer_checkBox"))
        self.sources_layer_verticalLayout.addWidget(self.sources_pts_layer_checkBox)
        self.sources_pts_layer_label = QtGui.QLabel(self.verticalLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sources_pts_layer_label.sizePolicy().hasHeightForWidth())
        self.sources_pts_layer_label.setSizePolicy(sizePolicy)
        self.sources_pts_layer_label.setObjectName(_fromUtf8("sources_pts_layer_label"))
        self.sources_layer_verticalLayout.addWidget(self.sources_pts_layer_label)
        self.sources_pts_layer_comboBox = QtGui.QComboBox(self.verticalLayoutWidget_3)
        self.sources_pts_layer_comboBox.setObjectName(_fromUtf8("sources_pts_layer_comboBox"))
        self.sources_layer_verticalLayout.addWidget(self.sources_pts_layer_comboBox)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.sources_layer_verticalLayout.addItem(spacerItem)
        self.sources_roads_layer_checkBox = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        self.sources_roads_layer_checkBox.setEnabled(True)
        self.sources_roads_layer_checkBox.setChecked(False)
        self.sources_roads_layer_checkBox.setObjectName(_fromUtf8("sources_roads_layer_checkBox"))
        self.sources_layer_verticalLayout.addWidget(self.sources_roads_layer_checkBox)
        self.sources_roads_layer_label = QtGui.QLabel(self.verticalLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sources_roads_layer_label.sizePolicy().hasHeightForWidth())
        self.sources_roads_layer_label.setSizePolicy(sizePolicy)
        self.sources_roads_layer_label.setObjectName(_fromUtf8("sources_roads_layer_label"))
        self.sources_layer_verticalLayout.addWidget(self.sources_roads_layer_label)
        self.sources_roads_layer_comboBox = QtGui.QComboBox(self.verticalLayoutWidget_3)
        self.sources_roads_layer_comboBox.setObjectName(_fromUtf8("sources_roads_layer_comboBox"))
        self.sources_layer_verticalLayout.addWidget(self.sources_roads_layer_comboBox)
        self.verticalLayoutWidget_4 = QtGui.QWidget(self.tabGeometry)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(60, 410, 481, 71))
        self.verticalLayoutWidget_4.setObjectName(_fromUtf8("verticalLayoutWidget_4"))
        self.buildings_layer_verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget_4)
        self.buildings_layer_verticalLayout.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.buildings_layer_verticalLayout.setMargin(0)
        self.buildings_layer_verticalLayout.setObjectName(_fromUtf8("buildings_layer_verticalLayout"))
        self.buildings_layer_label = QtGui.QLabel(self.verticalLayoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buildings_layer_label.sizePolicy().hasHeightForWidth())
        self.buildings_layer_label.setSizePolicy(sizePolicy)
        self.buildings_layer_label.setObjectName(_fromUtf8("buildings_layer_label"))
        self.buildings_layer_verticalLayout.addWidget(self.buildings_layer_label)
        self.buildings_layer_comboBox = QtGui.QComboBox(self.verticalLayoutWidget_4)
        self.buildings_layer_comboBox.setObjectName(_fromUtf8("buildings_layer_comboBox"))
        self.buildings_layer_verticalLayout.addWidget(self.buildings_layer_comboBox)
        self.sources_pts_pushButton = QtGui.QPushButton(self.tabGeometry)
        self.sources_pts_pushButton.setGeometry(QtCore.QRect(570, 210, 85, 31))
        self.sources_pts_pushButton.setObjectName(_fromUtf8("sources_pts_pushButton"))
        self.sources_roads_pushButton = QtGui.QPushButton(self.tabGeometry)
        self.sources_roads_pushButton.setGeometry(QtCore.QRect(570, 310, 85, 31))
        self.sources_roads_pushButton.setObjectName(_fromUtf8("sources_roads_pushButton"))
        self.receivers_layer_title = QtGui.QLabel(self.tabGeometry)
        self.receivers_layer_title.setGeometry(QtCore.QRect(20, 30, 221, 17))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.receivers_layer_title.sizePolicy().hasHeightForWidth())
        self.receivers_layer_title.setSizePolicy(sizePolicy)
        self.receivers_layer_title.setObjectName(_fromUtf8("receivers_layer_title"))
        self.sources_layer_title = QtGui.QLabel(self.tabGeometry)
        self.sources_layer_title.setGeometry(QtCore.QRect(20, 133, 261, 17))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sources_layer_title.sizePolicy().hasHeightForWidth())
        self.sources_layer_title.setSizePolicy(sizePolicy)
        self.sources_layer_title.setObjectName(_fromUtf8("sources_layer_title"))
        self.buildings_layer_checkBox = QtGui.QCheckBox(self.tabGeometry)
        self.buildings_layer_checkBox.setEnabled(True)
        self.buildings_layer_checkBox.setGeometry(QtCore.QRect(20, 380, 469, 22))
        self.buildings_layer_checkBox.setChecked(False)
        self.buildings_layer_checkBox.setObjectName(_fromUtf8("buildings_layer_checkBox"))
        self.tabWidget.addTab(self.tabGeometry, _fromUtf8(""))
        self.tabOptions = QtGui.QWidget()
        self.tabOptions.setObjectName(_fromUtf8("tabOptions"))
        self.horizontalLayoutWidget_3 = QtGui.QWidget(self.tabOptions)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(30, 37, 311, 35))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.research_ray_label = QtGui.QLabel(self.horizontalLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.research_ray_label.sizePolicy().hasHeightForWidth())
        self.research_ray_label.setSizePolicy(sizePolicy)
        self.research_ray_label.setMinimumSize(QtCore.QSize(200, 0))
        self.research_ray_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.research_ray_label.setObjectName(_fromUtf8("research_ray_label"))
        self.horizontalLayout_2.addWidget(self.research_ray_label)
        self.research_ray_comboBox = QtGui.QComboBox(self.horizontalLayoutWidget_3)
        self.research_ray_comboBox.setMinimumSize(QtCore.QSize(100, 0))
        self.research_ray_comboBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.research_ray_comboBox.setObjectName(_fromUtf8("research_ray_comboBox"))
        self.horizontalLayout_2.addWidget(self.research_ray_comboBox)
        self.L_den_checkBox = QtGui.QCheckBox(self.tabOptions)
        self.L_den_checkBox.setGeometry(QtCore.QRect(30, 180, 171, 20))
        self.L_den_checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.L_den_checkBox.setChecked(False)
        self.L_den_checkBox.setObjectName(_fromUtf8("L_den_checkBox"))
        self.L_den_hours_label = QtGui.QLabel(self.tabOptions)
        self.L_den_hours_label.setGeometry(QtCore.QRect(121, 210, 91, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.L_den_hours_label.sizePolicy().hasHeightForWidth())
        self.L_den_hours_label.setSizePolicy(sizePolicy)
        self.L_den_hours_label.setObjectName(_fromUtf8("L_den_hours_label"))
        self.L_den_penalty_label = QtGui.QLabel(self.tabOptions)
        self.L_den_penalty_label.setGeometry(QtCore.QRect(216, 210, 111, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.L_den_penalty_label.sizePolicy().hasHeightForWidth())
        self.L_den_penalty_label.setSizePolicy(sizePolicy)
        self.L_den_penalty_label.setObjectName(_fromUtf8("L_den_penalty_label"))
        self.L_den_day_label = QtGui.QLabel(self.tabOptions)
        self.L_den_day_label.setGeometry(QtCore.QRect(60, 230, 61, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.L_den_day_label.sizePolicy().hasHeightForWidth())
        self.L_den_day_label.setSizePolicy(sizePolicy)
        self.L_den_day_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.L_den_day_label.setObjectName(_fromUtf8("L_den_day_label"))
        self.L_den_nig_label = QtGui.QLabel(self.tabOptions)
        self.L_den_nig_label.setGeometry(QtCore.QRect(60, 280, 61, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.L_den_nig_label.sizePolicy().hasHeightForWidth())
        self.L_den_nig_label.setSizePolicy(sizePolicy)
        self.L_den_nig_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.L_den_nig_label.setObjectName(_fromUtf8("L_den_nig_label"))
        self.L_eve_penalty_spinBox = QtGui.QSpinBox(self.tabOptions)
        self.L_eve_penalty_spinBox.setGeometry(QtCore.QRect(234, 255, 51, 22))
        self.L_eve_penalty_spinBox.setMinimum(0)
        self.L_eve_penalty_spinBox.setProperty("value", 5)
        self.L_eve_penalty_spinBox.setObjectName(_fromUtf8("L_eve_penalty_spinBox"))
        self.L_den_eve_label = QtGui.QLabel(self.tabOptions)
        self.L_den_eve_label.setGeometry(QtCore.QRect(60, 256, 61, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.L_den_eve_label.sizePolicy().hasHeightForWidth())
        self.L_den_eve_label.setSizePolicy(sizePolicy)
        self.L_den_eve_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.L_den_eve_label.setObjectName(_fromUtf8("L_den_eve_label"))
        self.L_nig_penalty_spinBox = QtGui.QSpinBox(self.tabOptions)
        self.L_nig_penalty_spinBox.setGeometry(QtCore.QRect(234, 280, 51, 22))
        self.L_nig_penalty_spinBox.setMinimum(0)
        self.L_nig_penalty_spinBox.setProperty("value", 10)
        self.L_nig_penalty_spinBox.setObjectName(_fromUtf8("L_nig_penalty_spinBox"))
        self.L_day_penalty_spinBox = QtGui.QSpinBox(self.tabOptions)
        self.L_day_penalty_spinBox.setGeometry(QtCore.QRect(234, 230, 51, 22))
        self.L_day_penalty_spinBox.setMinimum(0)
        self.L_day_penalty_spinBox.setObjectName(_fromUtf8("L_day_penalty_spinBox"))
        self.L_nig_hours_spinBox = QtGui.QSpinBox(self.tabOptions)
        self.L_nig_hours_spinBox.setGeometry(QtCore.QRect(134, 280, 51, 22))
        self.L_nig_hours_spinBox.setMaximum(24)
        self.L_nig_hours_spinBox.setProperty("value", 8)
        self.L_nig_hours_spinBox.setObjectName(_fromUtf8("L_nig_hours_spinBox"))
        self.L_eve_hours_spinBox = QtGui.QSpinBox(self.tabOptions)
        self.L_eve_hours_spinBox.setGeometry(QtCore.QRect(134, 255, 51, 22))
        self.L_eve_hours_spinBox.setMaximum(24)
        self.L_eve_hours_spinBox.setProperty("value", 2)
        self.L_eve_hours_spinBox.setObjectName(_fromUtf8("L_eve_hours_spinBox"))
        self.L_day_hours_spinBox = QtGui.QSpinBox(self.tabOptions)
        self.L_day_hours_spinBox.setGeometry(QtCore.QRect(134, 230, 51, 22))
        self.L_day_hours_spinBox.setMaximum(24)
        self.L_day_hours_spinBox.setProperty("value", 14)
        self.L_day_hours_spinBox.setObjectName(_fromUtf8("L_day_hours_spinBox"))
        self.verticalLayoutWidget_8 = QtGui.QWidget(self.tabOptions)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(30, 350, 771, 61))
        self.verticalLayoutWidget_8.setObjectName(_fromUtf8("verticalLayoutWidget_8"))
        self.rays_layer_verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget_8)
        self.rays_layer_verticalLayout_3.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.rays_layer_verticalLayout_3.setMargin(0)
        self.rays_layer_verticalLayout_3.setObjectName(_fromUtf8("rays_layer_verticalLayout_3"))
        self.save_settings_checkBox = QtGui.QCheckBox(self.verticalLayoutWidget_8)
        self.save_settings_checkBox.setEnabled(True)
        self.save_settings_checkBox.setChecked(False)
        self.save_settings_checkBox.setObjectName(_fromUtf8("save_settings_checkBox"))
        self.rays_layer_verticalLayout_3.addWidget(self.save_settings_checkBox)
        self.rays_layer_horizontalLayout_3 = QtGui.QHBoxLayout()
        self.rays_layer_horizontalLayout_3.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.rays_layer_horizontalLayout_3.setObjectName(_fromUtf8("rays_layer_horizontalLayout_3"))
        self.save_settings_lineEdit = QtGui.QLineEdit(self.verticalLayoutWidget_8)
        self.save_settings_lineEdit.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_settings_lineEdit.sizePolicy().hasHeightForWidth())
        self.save_settings_lineEdit.setSizePolicy(sizePolicy)
        self.save_settings_lineEdit.setObjectName(_fromUtf8("save_settings_lineEdit"))
        self.rays_layer_horizontalLayout_3.addWidget(self.save_settings_lineEdit)
        self.save_settings_pushButton = QtGui.QPushButton(self.verticalLayoutWidget_8)
        self.save_settings_pushButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_settings_pushButton.sizePolicy().hasHeightForWidth())
        self.save_settings_pushButton.setSizePolicy(sizePolicy)
        self.save_settings_pushButton.setObjectName(_fromUtf8("save_settings_pushButton"))
        self.rays_layer_horizontalLayout_3.addWidget(self.save_settings_pushButton)
        self.rays_layer_verticalLayout_3.addLayout(self.rays_layer_horizontalLayout_3)
        self.line = QtGui.QFrame(self.tabOptions)
        self.line.setGeometry(QtCore.QRect(30, 80, 761, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(self.tabOptions)
        self.line_2.setGeometry(QtCore.QRect(30, 320, 761, 20))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.line_3 = QtGui.QFrame(self.tabOptions)
        self.line_3.setGeometry(QtCore.QRect(30, 150, 761, 20))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.horizontalLayoutWidget_4 = QtGui.QWidget(self.tabOptions)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(30, 108, 311, 35))
        self.horizontalLayoutWidget_4.setObjectName(_fromUtf8("horizontalLayoutWidget_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.research_ray_label_2 = QtGui.QLabel(self.horizontalLayoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.research_ray_label_2.sizePolicy().hasHeightForWidth())
        self.research_ray_label_2.setSizePolicy(sizePolicy)
        self.research_ray_label_2.setMinimumSize(QtCore.QSize(200, 0))
        self.research_ray_label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.research_ray_label_2.setObjectName(_fromUtf8("research_ray_label_2"))
        self.horizontalLayout_4.addWidget(self.research_ray_label_2)
        self.temperature_comboBox = QtGui.QComboBox(self.horizontalLayoutWidget_4)
        self.temperature_comboBox.setMinimumSize(QtCore.QSize(100, 0))
        self.temperature_comboBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.temperature_comboBox.setObjectName(_fromUtf8("temperature_comboBox"))
        self.horizontalLayout_4.addWidget(self.temperature_comboBox)
        self.horizontalLayoutWidget_5 = QtGui.QWidget(self.tabOptions)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(450, 108, 311, 35))
        self.horizontalLayoutWidget_5.setObjectName(_fromUtf8("horizontalLayoutWidget_5"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_9.setMargin(0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.research_ray_label_3 = QtGui.QLabel(self.horizontalLayoutWidget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.research_ray_label_3.sizePolicy().hasHeightForWidth())
        self.research_ray_label_3.setSizePolicy(sizePolicy)
        self.research_ray_label_3.setMinimumSize(QtCore.QSize(200, 0))
        self.research_ray_label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.research_ray_label_3.setObjectName(_fromUtf8("research_ray_label_3"))
        self.horizontalLayout_9.addWidget(self.research_ray_label_3)
        self.humidity_comboBox = QtGui.QComboBox(self.horizontalLayoutWidget_5)
        self.humidity_comboBox.setMinimumSize(QtCore.QSize(100, 0))
        self.humidity_comboBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.humidity_comboBox.setObjectName(_fromUtf8("humidity_comboBox"))
        self.horizontalLayout_9.addWidget(self.humidity_comboBox)
        self.line_4 = QtGui.QFrame(self.tabOptions)
        self.line_4.setGeometry(QtCore.QRect(30, 420, 761, 20))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.tabWidget.addTab(self.tabOptions, _fromUtf8(""))
        self.tabDebug = QtGui.QWidget()
        self.tabDebug.setObjectName(_fromUtf8("tabDebug"))
        self.label_14 = QtGui.QLabel(self.tabDebug)
        self.label_14.setGeometry(QtCore.QRect(30, 30, 641, 17))
        self.label_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayoutWidget_12 = QtGui.QWidget(self.tabDebug)
        self.verticalLayoutWidget_12.setGeometry(QtCore.QRect(21, 200, 771, 61))
        self.verticalLayoutWidget_12.setObjectName(_fromUtf8("verticalLayoutWidget_12"))
        self.rays_layer_verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_12)
        self.rays_layer_verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.rays_layer_verticalLayout_2.setMargin(0)
        self.rays_layer_verticalLayout_2.setObjectName(_fromUtf8("rays_layer_verticalLayout_2"))
        self.diff_rays_layer_checkBox = QtGui.QCheckBox(self.verticalLayoutWidget_12)
        self.diff_rays_layer_checkBox.setEnabled(True)
        self.diff_rays_layer_checkBox.setChecked(False)
        self.diff_rays_layer_checkBox.setObjectName(_fromUtf8("diff_rays_layer_checkBox"))
        self.rays_layer_verticalLayout_2.addWidget(self.diff_rays_layer_checkBox)
        self.rays_layer_horizontalLayout_2 = QtGui.QHBoxLayout()
        self.rays_layer_horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.rays_layer_horizontalLayout_2.setObjectName(_fromUtf8("rays_layer_horizontalLayout_2"))
        self.diff_rays_layer_lineEdit = QtGui.QLineEdit(self.verticalLayoutWidget_12)
        self.diff_rays_layer_lineEdit.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.diff_rays_layer_lineEdit.sizePolicy().hasHeightForWidth())
        self.diff_rays_layer_lineEdit.setSizePolicy(sizePolicy)
        self.diff_rays_layer_lineEdit.setObjectName(_fromUtf8("diff_rays_layer_lineEdit"))
        self.rays_layer_horizontalLayout_2.addWidget(self.diff_rays_layer_lineEdit)
        self.diff_rays_layer_pushButton = QtGui.QPushButton(self.verticalLayoutWidget_12)
        self.diff_rays_layer_pushButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.diff_rays_layer_pushButton.sizePolicy().hasHeightForWidth())
        self.diff_rays_layer_pushButton.setSizePolicy(sizePolicy)
        self.diff_rays_layer_pushButton.setObjectName(_fromUtf8("diff_rays_layer_pushButton"))
        self.rays_layer_horizontalLayout_2.addWidget(self.diff_rays_layer_pushButton)
        self.rays_layer_verticalLayout_2.addLayout(self.rays_layer_horizontalLayout_2)
        self.verticalLayoutWidget_7 = QtGui.QWidget(self.tabDebug)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(21, 110, 771, 61))
        self.verticalLayoutWidget_7.setObjectName(_fromUtf8("verticalLayoutWidget_7"))
        self.rays_layer_verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget_7)
        self.rays_layer_verticalLayout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.rays_layer_verticalLayout.setMargin(0)
        self.rays_layer_verticalLayout.setObjectName(_fromUtf8("rays_layer_verticalLayout"))
        self.rays_layer_checkBox = QtGui.QCheckBox(self.verticalLayoutWidget_7)
        self.rays_layer_checkBox.setEnabled(True)
        self.rays_layer_checkBox.setChecked(False)
        self.rays_layer_checkBox.setObjectName(_fromUtf8("rays_layer_checkBox"))
        self.rays_layer_verticalLayout.addWidget(self.rays_layer_checkBox)
        self.rays_layer_horizontalLayout = QtGui.QHBoxLayout()
        self.rays_layer_horizontalLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.rays_layer_horizontalLayout.setObjectName(_fromUtf8("rays_layer_horizontalLayout"))
        self.rays_layer_lineEdit = QtGui.QLineEdit(self.verticalLayoutWidget_7)
        self.rays_layer_lineEdit.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rays_layer_lineEdit.sizePolicy().hasHeightForWidth())
        self.rays_layer_lineEdit.setSizePolicy(sizePolicy)
        self.rays_layer_lineEdit.setObjectName(_fromUtf8("rays_layer_lineEdit"))
        self.rays_layer_horizontalLayout.addWidget(self.rays_layer_lineEdit)
        self.rays_layer_pushButton = QtGui.QPushButton(self.verticalLayoutWidget_7)
        self.rays_layer_pushButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rays_layer_pushButton.sizePolicy().hasHeightForWidth())
        self.rays_layer_pushButton.setSizePolicy(sizePolicy)
        self.rays_layer_pushButton.setObjectName(_fromUtf8("rays_layer_pushButton"))
        self.rays_layer_horizontalLayout.addWidget(self.rays_layer_pushButton)
        self.rays_layer_verticalLayout.addLayout(self.rays_layer_horizontalLayout)
        self.label_15 = QtGui.QLabel(self.tabDebug)
        self.label_15.setGeometry(QtCore.QRect(30, 60, 641, 17))
        self.label_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.tabWidget.addTab(self.tabDebug, _fromUtf8(""))
        self.tabCalculate = QtGui.QWidget()
        self.tabCalculate.setObjectName(_fromUtf8("tabCalculate"))
        self.buttonBox = QtGui.QDialogButtonBox(self.tabCalculate)
        self.buttonBox.setGeometry(QtCore.QRect(354, 510, 90, 27))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.calculate_pushButton = QtGui.QPushButton(self.tabCalculate)
        self.calculate_pushButton.setGeometry(QtCore.QRect(320, 40, 161, 61))
        self.calculate_pushButton.setObjectName(_fromUtf8("calculate_pushButton"))
        self.verticalLayoutWidget = QtGui.QWidget(self.tabCalculate)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(36, 130, 741, 341))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(200, 0))
        self.label.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.progressBar_create_dif = QtGui.QProgressBar(self.verticalLayoutWidget)
        self.progressBar_create_dif.setProperty("value", 0)
        self.progressBar_create_dif.setObjectName(_fromUtf8("progressBar_create_dif"))
        self.horizontalLayout.addWidget(self.progressBar_create_dif)
        self.label_time_create_dif = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_time_create_dif.sizePolicy().hasHeightForWidth())
        self.label_time_create_dif.setSizePolicy(sizePolicy)
        self.label_time_create_dif.setMinimumSize(QtCore.QSize(200, 0))
        self.label_time_create_dif.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_time_create_dif.setAlignment(QtCore.Qt.AlignCenter)
        self.label_time_create_dif.setObjectName(_fromUtf8("label_time_create_dif"))
        self.horizontalLayout.addWidget(self.label_time_create_dif)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(200, 0))
        self.label_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        self.progressBar_prepare_emi = QtGui.QProgressBar(self.verticalLayoutWidget)
        self.progressBar_prepare_emi.setProperty("value", 0)
        self.progressBar_prepare_emi.setObjectName(_fromUtf8("progressBar_prepare_emi"))
        self.horizontalLayout_3.addWidget(self.progressBar_prepare_emi)
        self.label_time_prepare_emi = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_time_prepare_emi.sizePolicy().hasHeightForWidth())
        self.label_time_prepare_emi.setSizePolicy(sizePolicy)
        self.label_time_prepare_emi.setMinimumSize(QtCore.QSize(200, 0))
        self.label_time_prepare_emi.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_time_prepare_emi.setAlignment(QtCore.Qt.AlignCenter)
        self.label_time_prepare_emi.setObjectName(_fromUtf8("label_time_prepare_emi"))
        self.horizontalLayout_3.addWidget(self.label_time_prepare_emi)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_4 = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(200, 0))
        self.label_4.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_5.addWidget(self.label_4)
        self.progressBar_recTOsou = QtGui.QProgressBar(self.verticalLayoutWidget)
        self.progressBar_recTOsou.setProperty("value", 0)
        self.progressBar_recTOsou.setObjectName(_fromUtf8("progressBar_recTOsou"))
        self.horizontalLayout_5.addWidget(self.progressBar_recTOsou)
        self.label_time_recTOsou = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_time_recTOsou.sizePolicy().hasHeightForWidth())
        self.label_time_recTOsou.setSizePolicy(sizePolicy)
        self.label_time_recTOsou.setMinimumSize(QtCore.QSize(200, 0))
        self.label_time_recTOsou.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_time_recTOsou.setAlignment(QtCore.Qt.AlignCenter)
        self.label_time_recTOsou.setObjectName(_fromUtf8("label_time_recTOsou"))
        self.horizontalLayout_5.addWidget(self.label_time_recTOsou)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_5 = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(200, 0))
        self.label_5.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_6.addWidget(self.label_5)
        self.progressBar_difTOsou = QtGui.QProgressBar(self.verticalLayoutWidget)
        self.progressBar_difTOsou.setProperty("value", 0)
        self.progressBar_difTOsou.setObjectName(_fromUtf8("progressBar_difTOsou"))
        self.horizontalLayout_6.addWidget(self.progressBar_difTOsou)
        self.label_time_difTOsou = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_time_difTOsou.sizePolicy().hasHeightForWidth())
        self.label_time_difTOsou.setSizePolicy(sizePolicy)
        self.label_time_difTOsou.setMinimumSize(QtCore.QSize(200, 0))
        self.label_time_difTOsou.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_time_difTOsou.setAlignment(QtCore.Qt.AlignCenter)
        self.label_time_difTOsou.setObjectName(_fromUtf8("label_time_difTOsou"))
        self.horizontalLayout_6.addWidget(self.label_time_difTOsou)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_6 = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(200, 0))
        self.label_6.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_7.addWidget(self.label_6)
        self.progressBar_recTOdif = QtGui.QProgressBar(self.verticalLayoutWidget)
        self.progressBar_recTOdif.setProperty("value", 0)
        self.progressBar_recTOdif.setObjectName(_fromUtf8("progressBar_recTOdif"))
        self.horizontalLayout_7.addWidget(self.progressBar_recTOdif)
        self.label_time_recTOdif = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_time_recTOdif.sizePolicy().hasHeightForWidth())
        self.label_time_recTOdif.setSizePolicy(sizePolicy)
        self.label_time_recTOdif.setMinimumSize(QtCore.QSize(200, 0))
        self.label_time_recTOdif.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_time_recTOdif.setAlignment(QtCore.Qt.AlignCenter)
        self.label_time_recTOdif.setObjectName(_fromUtf8("label_time_recTOdif"))
        self.horizontalLayout_7.addWidget(self.label_time_recTOdif)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_calculate = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_calculate.sizePolicy().hasHeightForWidth())
        self.label_calculate.setSizePolicy(sizePolicy)
        self.label_calculate.setMinimumSize(QtCore.QSize(200, 0))
        self.label_calculate.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_calculate.setAlignment(QtCore.Qt.AlignCenter)
        self.label_calculate.setObjectName(_fromUtf8("label_calculate"))
        self.horizontalLayout_8.addWidget(self.label_calculate)
        self.progressBar_calculate = QtGui.QProgressBar(self.verticalLayoutWidget)
        self.progressBar_calculate.setProperty("value", 0)
        self.progressBar_calculate.setObjectName(_fromUtf8("progressBar_calculate"))
        self.horizontalLayout_8.addWidget(self.progressBar_calculate)
        self.label_time_calculate = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_time_calculate.sizePolicy().hasHeightForWidth())
        self.label_time_calculate.setSizePolicy(sizePolicy)
        self.label_time_calculate.setMinimumSize(QtCore.QSize(200, 0))
        self.label_time_calculate.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_time_calculate.setAlignment(QtCore.Qt.AlignCenter)
        self.label_time_calculate.setObjectName(_fromUtf8("label_time_calculate"))
        self.horizontalLayout_8.addWidget(self.label_time_calculate)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.label_time_start = QtGui.QLabel(self.tabCalculate)
        self.label_time_start.setGeometry(QtCore.QRect(504, 42, 300, 17))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_time_start.sizePolicy().hasHeightForWidth())
        self.label_time_start.setSizePolicy(sizePolicy)
        self.label_time_start.setMinimumSize(QtCore.QSize(300, 0))
        self.label_time_start.setMaximumSize(QtCore.QSize(300, 16777215))
        self.label_time_start.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_time_start.setObjectName(_fromUtf8("label_time_start"))
        self.label_time_end = QtGui.QLabel(self.tabCalculate)
        self.label_time_end.setGeometry(QtCore.QRect(504, 62, 300, 17))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_time_end.sizePolicy().hasHeightForWidth())
        self.label_time_end.setSizePolicy(sizePolicy)
        self.label_time_end.setMinimumSize(QtCore.QSize(300, 0))
        self.label_time_end.setMaximumSize(QtCore.QSize(300, 16777215))
        self.label_time_end.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_time_end.setObjectName(_fromUtf8("label_time_end"))
        self.label_time_duration = QtGui.QLabel(self.tabCalculate)
        self.label_time_duration.setGeometry(QtCore.QRect(504, 82, 300, 17))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_time_duration.sizePolicy().hasHeightForWidth())
        self.label_time_duration.setSizePolicy(sizePolicy)
        self.label_time_duration.setMinimumSize(QtCore.QSize(300, 0))
        self.label_time_duration.setMaximumSize(QtCore.QSize(300, 16777215))
        self.label_time_duration.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_time_duration.setObjectName(_fromUtf8("label_time_duration"))
        self.tabWidget.addTab(self.tabCalculate, _fromUtf8(""))

        self.retranslateUi(CalculateNoiseLevels_window)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), CalculateNoiseLevels_window.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), CalculateNoiseLevels_window.reject)
        QtCore.QMetaObject.connectSlotsByName(CalculateNoiseLevels_window)

    def retranslateUi(self, CalculateNoiseLevels_window):
        CalculateNoiseLevels_window.setWindowTitle(_translate("CalculateNoiseLevels_window", "Calculate Noise Levels", None))
        self.label_8.setText(_translate("CalculateNoiseLevels_window", "This script calculates the noise levels. ", None))
        self.reload_last_settings_pushButton.setText(_translate("CalculateNoiseLevels_window", "Reload last Settings", None))
        self.label_9.setText(_translate("CalculateNoiseLevels_window", "Otherwise you can reload the last or a saved Setting file:", None))
        self.reload_saved_settings_pushButton.setText(_translate("CalculateNoiseLevels_window", "Reload a saved Settings file", None))
        self.label_10.setText(_translate("CalculateNoiseLevels_window", "Compile the next sections to calculate the levels:", None))
        self.label_11.setText(_translate("CalculateNoiseLevels_window", "1. INPUT: Insert the receivers, sources and buildings layers.", None))
        self.label_12.setText(_translate("CalculateNoiseLevels_window", "2. OPTIONS: Select some option settings as the research distance.", None))
        self.label_13.setText(_translate("CalculateNoiseLevels_window", "3. CALCULATE: Calculate the levels to the receivers.", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("CalculateNoiseLevels_window", "Start", None))
        self.receivers_layer_label.setText(_translate("CalculateNoiseLevels_window", "Choose a point layer as receiver", None))
        self.sources_pts_layer_checkBox.setText(_translate("CalculateNoiseLevels_window", "POINTS", None))
        self.sources_pts_layer_label.setText(_translate("CalculateNoiseLevels_window", "Choose a point layer as source", None))
        self.sources_roads_layer_checkBox.setText(_translate("CalculateNoiseLevels_window", "ROADS", None))
        self.sources_roads_layer_label.setText(_translate("CalculateNoiseLevels_window", "Choose a line layer as source", None))
        self.buildings_layer_label.setText(_translate("CalculateNoiseLevels_window", "Choose a polygon layer as buildings", None))
        self.sources_pts_pushButton.setText(_translate("CalculateNoiseLevels_window", "Details", None))
        self.sources_roads_pushButton.setText(_translate("CalculateNoiseLevels_window", "Details", None))
        self.receivers_layer_title.setText(_translate("CalculateNoiseLevels_window", "RECEIVERS", None))
        self.sources_layer_title.setText(_translate("CalculateNoiseLevels_window", "SOURCES", None))
        self.buildings_layer_checkBox.setText(_translate("CalculateNoiseLevels_window", "BUILDINGS", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabGeometry), _translate("CalculateNoiseLevels_window", "Input", None))
        self.research_ray_label.setText(_translate("CalculateNoiseLevels_window", "Research ray (m)", None))
        self.L_den_checkBox.setText(_translate("CalculateNoiseLevels_window", " L den  calculation", None))
        self.L_den_hours_label.setText(_translate("CalculateNoiseLevels_window", "Total hours", None))
        self.L_den_penalty_label.setText(_translate("CalculateNoiseLevels_window", "Penalizations (dB)", None))
        self.L_den_day_label.setText(_translate("CalculateNoiseLevels_window", "L day", None))
        self.L_den_nig_label.setText(_translate("CalculateNoiseLevels_window", "L nig", None))
        self.L_den_eve_label.setText(_translate("CalculateNoiseLevels_window", "L eve", None))
        self.save_settings_checkBox.setText(_translate("CalculateNoiseLevels_window", "Save current Settings in a xml file", None))
        self.save_settings_pushButton.setText(_translate("CalculateNoiseLevels_window", "Browse", None))
        self.research_ray_label_2.setText(_translate("CalculateNoiseLevels_window", "Temperature (Celsius degree)", None))
        self.research_ray_label_3.setText(_translate("CalculateNoiseLevels_window", "Relative humidity (%)", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabOptions), _translate("CalculateNoiseLevels_window", "Options", None))
        self.label_14.setText(_translate("CalculateNoiseLevels_window", "Create the sound rays layers if you want to control the single noise level contribution.", None))
        self.diff_rays_layer_checkBox.setText(_translate("CalculateNoiseLevels_window", "Create diffraction sound rays layer (output line layer)", None))
        self.diff_rays_layer_pushButton.setText(_translate("CalculateNoiseLevels_window", "Browse", None))
        self.rays_layer_checkBox.setText(_translate("CalculateNoiseLevels_window", "Create direct sound rays layer (output line layer)", None))
        self.rays_layer_pushButton.setText(_translate("CalculateNoiseLevels_window", "Browse", None))
        self.label_15.setText(_translate("CalculateNoiseLevels_window", "This operation can take a long time, select the rays creation only for little calculations.", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDebug), _translate("CalculateNoiseLevels_window", "Debug", None))
        self.calculate_pushButton.setText(_translate("CalculateNoiseLevels_window", "CALCULATE", None))
        self.label.setText(_translate("CalculateNoiseLevels_window", "Create diffraction points", None))
        self.label_time_create_dif.setText(_translate("CalculateNoiseLevels_window", "Done in HH:MM:SS.sss", None))
        self.label_2.setText(_translate("CalculateNoiseLevels_window", "Prepare emission points", None))
        self.label_time_prepare_emi.setText(_translate("CalculateNoiseLevels_window", "Done in HH:MM:SS.sss", None))
        self.label_4.setText(_translate("CalculateNoiseLevels_window", "Find receivers-sources rays", None))
        self.label_time_recTOsou.setText(_translate("CalculateNoiseLevels_window", "Done in HH:MM:SS.sss", None))
        self.label_5.setText(_translate("CalculateNoiseLevels_window", "Find diffractors-sources rays", None))
        self.label_time_difTOsou.setText(_translate("CalculateNoiseLevels_window", "Done in HH:MM:SS.sss", None))
        self.label_6.setText(_translate("CalculateNoiseLevels_window", "Find receivers-diffractors rays", None))
        self.label_time_recTOdif.setText(_translate("CalculateNoiseLevels_window", "Done in HH:MM:SS.sss", None))
        self.label_calculate.setText(_translate("CalculateNoiseLevels_window", "Calculate levels", None))
        self.label_time_calculate.setText(_translate("CalculateNoiseLevels_window", "Done in HH:MM:SS.sss", None))
        self.label_time_start.setText(_translate("CalculateNoiseLevels_window", "Done in HH:MM:SS.sss", None))
        self.label_time_end.setText(_translate("CalculateNoiseLevels_window", "Done in HH:MM:SS.sss", None))
        self.label_time_duration.setText(_translate("CalculateNoiseLevels_window", "Done in HH:MM:SS.sss", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCalculate), _translate("CalculateNoiseLevels_window", "Calculate", None))

