# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_CalculateNoiseLevels.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CalculateNoiseLevels_window(object):
    def setupUi(self, CalculateNoiseLevels_window):
        CalculateNoiseLevels_window.setObjectName("CalculateNoiseLevels_window")
        CalculateNoiseLevels_window.resize(848, 611)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CalculateNoiseLevels_window.sizePolicy().hasHeightForWidth())
        CalculateNoiseLevels_window.setSizePolicy(sizePolicy)
        CalculateNoiseLevels_window.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        CalculateNoiseLevels_window.setModal(False)
        self.tabWidget = QtWidgets.QTabWidget(CalculateNoiseLevels_window)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 831, 591))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(40, 50, 471, 17))
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.reload_last_settings_pushButton = QtWidgets.QPushButton(self.tab)
        self.reload_last_settings_pushButton.setGeometry(QtCore.QRect(300, 270, 191, 31))
        self.reload_last_settings_pushButton.setObjectName("reload_last_settings_pushButton")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(50, 220, 471, 17))
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.reload_saved_settings_pushButton = QtWidgets.QPushButton(self.tab)
        self.reload_saved_settings_pushButton.setGeometry(QtCore.QRect(260, 320, 251, 31))
        self.reload_saved_settings_pushButton.setObjectName("reload_saved_settings_pushButton")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(40, 80, 471, 17))
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(100, 110, 471, 17))
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(100, 130, 661, 17))
        self.label_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(100, 150, 661, 17))
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.tabWidget.addTab(self.tab, "")
        self.tabGeometry = QtWidgets.QWidget()
        self.tabGeometry.setObjectName("tabGeometry")
        self.widget = QtWidgets.QWidget(self.tabGeometry)
        self.widget.setGeometry(QtCore.QRect(10, 11, 801, 521))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.receivers_layer_title = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.receivers_layer_title.sizePolicy().hasHeightForWidth())
        self.receivers_layer_title.setSizePolicy(sizePolicy)
        self.receivers_layer_title.setObjectName("receivers_layer_title")
        self.verticalLayout_2.addWidget(self.receivers_layer_title)
        self.receivers_layer_label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.receivers_layer_label.sizePolicy().hasHeightForWidth())
        self.receivers_layer_label.setSizePolicy(sizePolicy)
        self.receivers_layer_label.setObjectName("receivers_layer_label")
        self.verticalLayout_2.addWidget(self.receivers_layer_label)
        self.receivers_layer_comboBox = QtWidgets.QComboBox(self.widget)
        self.receivers_layer_comboBox.setObjectName("receivers_layer_comboBox")
        self.verticalLayout_2.addWidget(self.receivers_layer_comboBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.sources_layer_title = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sources_layer_title.sizePolicy().hasHeightForWidth())
        self.sources_layer_title.setSizePolicy(sizePolicy)
        self.sources_layer_title.setObjectName("sources_layer_title")
        self.verticalLayout_2.addWidget(self.sources_layer_title)
        self.sources_pts_layer_checkBox = QtWidgets.QCheckBox(self.widget)
        self.sources_pts_layer_checkBox.setEnabled(True)
        self.sources_pts_layer_checkBox.setChecked(False)
        self.sources_pts_layer_checkBox.setObjectName("sources_pts_layer_checkBox")
        self.verticalLayout_2.addWidget(self.sources_pts_layer_checkBox)
        self.sources_pts_layer_label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sources_pts_layer_label.sizePolicy().hasHeightForWidth())
        self.sources_pts_layer_label.setSizePolicy(sizePolicy)
        self.sources_pts_layer_label.setObjectName("sources_pts_layer_label")
        self.verticalLayout_2.addWidget(self.sources_pts_layer_label)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.sources_pts_layer_comboBox = QtWidgets.QComboBox(self.widget)
        self.sources_pts_layer_comboBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(50)
        sizePolicy.setHeightForWidth(self.sources_pts_layer_comboBox.sizePolicy().hasHeightForWidth())
        self.sources_pts_layer_comboBox.setSizePolicy(sizePolicy)
        self.sources_pts_layer_comboBox.setObjectName("sources_pts_layer_comboBox")
        self.horizontalLayout_10.addWidget(self.sources_pts_layer_comboBox)
        self.sources_pts_pushButton = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sources_pts_pushButton.sizePolicy().hasHeightForWidth())
        self.sources_pts_pushButton.setSizePolicy(sizePolicy)
        self.sources_pts_pushButton.setObjectName("sources_pts_pushButton")
        self.horizontalLayout_10.addWidget(self.sources_pts_pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.sources_roads_layer_checkBox = QtWidgets.QCheckBox(self.widget)
        self.sources_roads_layer_checkBox.setEnabled(True)
        self.sources_roads_layer_checkBox.setChecked(False)
        self.sources_roads_layer_checkBox.setObjectName("sources_roads_layer_checkBox")
        self.verticalLayout_2.addWidget(self.sources_roads_layer_checkBox)
        self.sources_roads_layer_label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sources_roads_layer_label.sizePolicy().hasHeightForWidth())
        self.sources_roads_layer_label.setSizePolicy(sizePolicy)
        self.sources_roads_layer_label.setObjectName("sources_roads_layer_label")
        self.verticalLayout_2.addWidget(self.sources_roads_layer_label)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.sources_roads_layer_comboBox = QtWidgets.QComboBox(self.widget)
        self.sources_roads_layer_comboBox.setObjectName("sources_roads_layer_comboBox")
        self.horizontalLayout_11.addWidget(self.sources_roads_layer_comboBox)
        self.sources_roads_pushButton = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sources_roads_pushButton.sizePolicy().hasHeightForWidth())
        self.sources_roads_pushButton.setSizePolicy(sizePolicy)
        self.sources_roads_pushButton.setObjectName("sources_roads_pushButton")
        self.horizontalLayout_11.addWidget(self.sources_roads_pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.buildings_layer_checkBox = QtWidgets.QCheckBox(self.widget)
        self.buildings_layer_checkBox.setEnabled(True)
        self.buildings_layer_checkBox.setChecked(False)
        self.buildings_layer_checkBox.setObjectName("buildings_layer_checkBox")
        self.verticalLayout_2.addWidget(self.buildings_layer_checkBox)
        self.buildings_layer_label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buildings_layer_label.sizePolicy().hasHeightForWidth())
        self.buildings_layer_label.setSizePolicy(sizePolicy)
        self.buildings_layer_label.setObjectName("buildings_layer_label")
        self.verticalLayout_2.addWidget(self.buildings_layer_label)
        self.buildings_layer_comboBox = QtWidgets.QComboBox(self.widget)
        self.buildings_layer_comboBox.setObjectName("buildings_layer_comboBox")
        self.verticalLayout_2.addWidget(self.buildings_layer_comboBox)
        self.tabWidget.addTab(self.tabGeometry, "")
        self.tabOptions = QtWidgets.QWidget()
        self.tabOptions.setObjectName("tabOptions")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.tabOptions)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(30, 37, 311, 51))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.research_ray_label = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.research_ray_label.sizePolicy().hasHeightForWidth())
        self.research_ray_label.setSizePolicy(sizePolicy)
        self.research_ray_label.setMinimumSize(QtCore.QSize(200, 0))
        self.research_ray_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.research_ray_label.setObjectName("research_ray_label")
        self.horizontalLayout_2.addWidget(self.research_ray_label)
        self.research_ray_comboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget_3)
        self.research_ray_comboBox.setMinimumSize(QtCore.QSize(100, 0))
        self.research_ray_comboBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.research_ray_comboBox.setObjectName("research_ray_comboBox")
        self.horizontalLayout_2.addWidget(self.research_ray_comboBox)
        self.L_den_checkBox = QtWidgets.QCheckBox(self.tabOptions)
        self.L_den_checkBox.setGeometry(QtCore.QRect(30, 180, 171, 20))
        self.L_den_checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.L_den_checkBox.setChecked(False)
        self.L_den_checkBox.setObjectName("L_den_checkBox")
        self.L_den_hours_label = QtWidgets.QLabel(self.tabOptions)
        self.L_den_hours_label.setGeometry(QtCore.QRect(121, 210, 91, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.L_den_hours_label.sizePolicy().hasHeightForWidth())
        self.L_den_hours_label.setSizePolicy(sizePolicy)
        self.L_den_hours_label.setObjectName("L_den_hours_label")
        self.L_den_penalty_label = QtWidgets.QLabel(self.tabOptions)
        self.L_den_penalty_label.setGeometry(QtCore.QRect(216, 210, 111, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.L_den_penalty_label.sizePolicy().hasHeightForWidth())
        self.L_den_penalty_label.setSizePolicy(sizePolicy)
        self.L_den_penalty_label.setObjectName("L_den_penalty_label")
        self.L_den_day_label = QtWidgets.QLabel(self.tabOptions)
        self.L_den_day_label.setGeometry(QtCore.QRect(60, 230, 61, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.L_den_day_label.sizePolicy().hasHeightForWidth())
        self.L_den_day_label.setSizePolicy(sizePolicy)
        self.L_den_day_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.L_den_day_label.setObjectName("L_den_day_label")
        self.L_den_nig_label = QtWidgets.QLabel(self.tabOptions)
        self.L_den_nig_label.setGeometry(QtCore.QRect(60, 280, 61, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.L_den_nig_label.sizePolicy().hasHeightForWidth())
        self.L_den_nig_label.setSizePolicy(sizePolicy)
        self.L_den_nig_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.L_den_nig_label.setObjectName("L_den_nig_label")
        self.L_eve_penalty_spinBox = QtWidgets.QSpinBox(self.tabOptions)
        self.L_eve_penalty_spinBox.setGeometry(QtCore.QRect(234, 255, 51, 22))
        self.L_eve_penalty_spinBox.setMinimum(0)
        self.L_eve_penalty_spinBox.setProperty("value", 5)
        self.L_eve_penalty_spinBox.setObjectName("L_eve_penalty_spinBox")
        self.L_den_eve_label = QtWidgets.QLabel(self.tabOptions)
        self.L_den_eve_label.setGeometry(QtCore.QRect(60, 256, 61, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.L_den_eve_label.sizePolicy().hasHeightForWidth())
        self.L_den_eve_label.setSizePolicy(sizePolicy)
        self.L_den_eve_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.L_den_eve_label.setObjectName("L_den_eve_label")
        self.L_nig_penalty_spinBox = QtWidgets.QSpinBox(self.tabOptions)
        self.L_nig_penalty_spinBox.setGeometry(QtCore.QRect(234, 280, 51, 22))
        self.L_nig_penalty_spinBox.setMinimum(0)
        self.L_nig_penalty_spinBox.setProperty("value", 10)
        self.L_nig_penalty_spinBox.setObjectName("L_nig_penalty_spinBox")
        self.L_day_penalty_spinBox = QtWidgets.QSpinBox(self.tabOptions)
        self.L_day_penalty_spinBox.setGeometry(QtCore.QRect(234, 230, 51, 22))
        self.L_day_penalty_spinBox.setMinimum(0)
        self.L_day_penalty_spinBox.setObjectName("L_day_penalty_spinBox")
        self.L_nig_hours_spinBox = QtWidgets.QSpinBox(self.tabOptions)
        self.L_nig_hours_spinBox.setGeometry(QtCore.QRect(134, 280, 51, 22))
        self.L_nig_hours_spinBox.setMaximum(24)
        self.L_nig_hours_spinBox.setProperty("value", 8)
        self.L_nig_hours_spinBox.setObjectName("L_nig_hours_spinBox")
        self.L_eve_hours_spinBox = QtWidgets.QSpinBox(self.tabOptions)
        self.L_eve_hours_spinBox.setGeometry(QtCore.QRect(134, 255, 51, 22))
        self.L_eve_hours_spinBox.setMaximum(24)
        self.L_eve_hours_spinBox.setProperty("value", 2)
        self.L_eve_hours_spinBox.setObjectName("L_eve_hours_spinBox")
        self.L_day_hours_spinBox = QtWidgets.QSpinBox(self.tabOptions)
        self.L_day_hours_spinBox.setGeometry(QtCore.QRect(134, 230, 51, 22))
        self.L_day_hours_spinBox.setMaximum(24)
        self.L_day_hours_spinBox.setProperty("value", 14)
        self.L_day_hours_spinBox.setObjectName("L_day_hours_spinBox")
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.tabOptions)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(30, 350, 771, 91))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.rays_layer_verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.rays_layer_verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.rays_layer_verticalLayout_3.setObjectName("rays_layer_verticalLayout_3")
        self.save_settings_checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_8)
        self.save_settings_checkBox.setEnabled(True)
        self.save_settings_checkBox.setChecked(False)
        self.save_settings_checkBox.setObjectName("save_settings_checkBox")
        self.rays_layer_verticalLayout_3.addWidget(self.save_settings_checkBox)
        self.rays_layer_horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.rays_layer_horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.rays_layer_horizontalLayout_3.setObjectName("rays_layer_horizontalLayout_3")
        self.save_settings_lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_8)
        self.save_settings_lineEdit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_settings_lineEdit.sizePolicy().hasHeightForWidth())
        self.save_settings_lineEdit.setSizePolicy(sizePolicy)
        self.save_settings_lineEdit.setObjectName("save_settings_lineEdit")
        self.rays_layer_horizontalLayout_3.addWidget(self.save_settings_lineEdit)
        self.save_settings_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_8)
        self.save_settings_pushButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_settings_pushButton.sizePolicy().hasHeightForWidth())
        self.save_settings_pushButton.setSizePolicy(sizePolicy)
        self.save_settings_pushButton.setObjectName("save_settings_pushButton")
        self.rays_layer_horizontalLayout_3.addWidget(self.save_settings_pushButton)
        self.rays_layer_verticalLayout_3.addLayout(self.rays_layer_horizontalLayout_3)
        self.line = QtWidgets.QFrame(self.tabOptions)
        self.line.setGeometry(QtCore.QRect(30, 80, 761, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.tabOptions)
        self.line_2.setGeometry(QtCore.QRect(30, 320, 761, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.tabOptions)
        self.line_3.setGeometry(QtCore.QRect(30, 150, 761, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.tabOptions)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(30, 108, 311, 41))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.research_ray_label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.research_ray_label_2.sizePolicy().hasHeightForWidth())
        self.research_ray_label_2.setSizePolicy(sizePolicy)
        self.research_ray_label_2.setMinimumSize(QtCore.QSize(200, 0))
        self.research_ray_label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.research_ray_label_2.setObjectName("research_ray_label_2")
        self.horizontalLayout_4.addWidget(self.research_ray_label_2)
        self.temperature_comboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget_4)
        self.temperature_comboBox.setMinimumSize(QtCore.QSize(100, 0))
        self.temperature_comboBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.temperature_comboBox.setObjectName("temperature_comboBox")
        self.horizontalLayout_4.addWidget(self.temperature_comboBox)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.tabOptions)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(450, 108, 311, 41))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.research_ray_label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.research_ray_label_3.sizePolicy().hasHeightForWidth())
        self.research_ray_label_3.setSizePolicy(sizePolicy)
        self.research_ray_label_3.setMinimumSize(QtCore.QSize(200, 0))
        self.research_ray_label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.research_ray_label_3.setObjectName("research_ray_label_3")
        self.horizontalLayout_9.addWidget(self.research_ray_label_3)
        self.humidity_comboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget_5)
        self.humidity_comboBox.setMinimumSize(QtCore.QSize(100, 0))
        self.humidity_comboBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.humidity_comboBox.setObjectName("humidity_comboBox")
        self.horizontalLayout_9.addWidget(self.humidity_comboBox)
        self.line_4 = QtWidgets.QFrame(self.tabOptions)
        self.line_4.setGeometry(QtCore.QRect(30, 420, 761, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.tabWidget.addTab(self.tabOptions, "")
        self.tabDebug = QtWidgets.QWidget()
        self.tabDebug.setObjectName("tabDebug")
        self.label_14 = QtWidgets.QLabel(self.tabDebug)
        self.label_14.setGeometry(QtCore.QRect(30, 30, 641, 17))
        self.label_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayoutWidget_12 = QtWidgets.QWidget(self.tabDebug)
        self.verticalLayoutWidget_12.setGeometry(QtCore.QRect(20, 230, 771, 91))
        self.verticalLayoutWidget_12.setObjectName("verticalLayoutWidget_12")
        self.rays_layer_verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_12)
        self.rays_layer_verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.rays_layer_verticalLayout_2.setObjectName("rays_layer_verticalLayout_2")
        self.diff_rays_layer_checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_12)
        self.diff_rays_layer_checkBox.setEnabled(True)
        self.diff_rays_layer_checkBox.setChecked(False)
        self.diff_rays_layer_checkBox.setObjectName("diff_rays_layer_checkBox")
        self.rays_layer_verticalLayout_2.addWidget(self.diff_rays_layer_checkBox)
        self.rays_layer_horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.rays_layer_horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.rays_layer_horizontalLayout_2.setObjectName("rays_layer_horizontalLayout_2")
        self.diff_rays_layer_lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_12)
        self.diff_rays_layer_lineEdit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.diff_rays_layer_lineEdit.sizePolicy().hasHeightForWidth())
        self.diff_rays_layer_lineEdit.setSizePolicy(sizePolicy)
        self.diff_rays_layer_lineEdit.setObjectName("diff_rays_layer_lineEdit")
        self.rays_layer_horizontalLayout_2.addWidget(self.diff_rays_layer_lineEdit)
        self.diff_rays_layer_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_12)
        self.diff_rays_layer_pushButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.diff_rays_layer_pushButton.sizePolicy().hasHeightForWidth())
        self.diff_rays_layer_pushButton.setSizePolicy(sizePolicy)
        self.diff_rays_layer_pushButton.setObjectName("diff_rays_layer_pushButton")
        self.rays_layer_horizontalLayout_2.addWidget(self.diff_rays_layer_pushButton)
        self.rays_layer_verticalLayout_2.addLayout(self.rays_layer_horizontalLayout_2)
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.tabDebug)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(21, 110, 771, 91))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.rays_layer_verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.rays_layer_verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.rays_layer_verticalLayout.setObjectName("rays_layer_verticalLayout")
        self.rays_layer_checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_7)
        self.rays_layer_checkBox.setEnabled(True)
        self.rays_layer_checkBox.setChecked(False)
        self.rays_layer_checkBox.setObjectName("rays_layer_checkBox")
        self.rays_layer_verticalLayout.addWidget(self.rays_layer_checkBox)
        self.rays_layer_horizontalLayout = QtWidgets.QHBoxLayout()
        self.rays_layer_horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.rays_layer_horizontalLayout.setObjectName("rays_layer_horizontalLayout")
        self.rays_layer_lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_7)
        self.rays_layer_lineEdit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rays_layer_lineEdit.sizePolicy().hasHeightForWidth())
        self.rays_layer_lineEdit.setSizePolicy(sizePolicy)
        self.rays_layer_lineEdit.setObjectName("rays_layer_lineEdit")
        self.rays_layer_horizontalLayout.addWidget(self.rays_layer_lineEdit)
        self.rays_layer_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.rays_layer_pushButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rays_layer_pushButton.sizePolicy().hasHeightForWidth())
        self.rays_layer_pushButton.setSizePolicy(sizePolicy)
        self.rays_layer_pushButton.setObjectName("rays_layer_pushButton")
        self.rays_layer_horizontalLayout.addWidget(self.rays_layer_pushButton)
        self.rays_layer_verticalLayout.addLayout(self.rays_layer_horizontalLayout)
        self.label_15 = QtWidgets.QLabel(self.tabDebug)
        self.label_15.setGeometry(QtCore.QRect(30, 60, 641, 17))
        self.label_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.tabWidget.addTab(self.tabDebug, "")
        self.tabCalculate = QtWidgets.QWidget()
        self.tabCalculate.setObjectName("tabCalculate")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.tabCalculate)
        self.buttonBox.setGeometry(QtCore.QRect(354, 506, 90, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.calculate_pushButton = QtWidgets.QPushButton(self.tabCalculate)
        self.calculate_pushButton.setGeometry(QtCore.QRect(320, 40, 161, 61))
        self.calculate_pushButton.setObjectName("calculate_pushButton")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tabCalculate)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(36, 130, 741, 361))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(200, 0))
        self.label.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.progressBar_create_dif = QtWidgets.QProgressBar(self.verticalLayoutWidget)
        self.progressBar_create_dif.setProperty("value", 0)
        self.progressBar_create_dif.setObjectName("progressBar_create_dif")
        self.horizontalLayout.addWidget(self.progressBar_create_dif)
        self.label_time_create_dif = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_time_create_dif.sizePolicy().hasHeightForWidth())
        self.label_time_create_dif.setSizePolicy(sizePolicy)
        self.label_time_create_dif.setMinimumSize(QtCore.QSize(200, 0))
        self.label_time_create_dif.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_time_create_dif.setAlignment(QtCore.Qt.AlignCenter)
        self.label_time_create_dif.setObjectName("label_time_create_dif")
        self.horizontalLayout.addWidget(self.label_time_create_dif)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(200, 0))
        self.label_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.progressBar_prepare_emi = QtWidgets.QProgressBar(self.verticalLayoutWidget)
        self.progressBar_prepare_emi.setProperty("value", 0)
        self.progressBar_prepare_emi.setObjectName("progressBar_prepare_emi")
        self.horizontalLayout_3.addWidget(self.progressBar_prepare_emi)
        self.label_time_prepare_emi = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_time_prepare_emi.sizePolicy().hasHeightForWidth())
        self.label_time_prepare_emi.setSizePolicy(sizePolicy)
        self.label_time_prepare_emi.setMinimumSize(QtCore.QSize(200, 0))
        self.label_time_prepare_emi.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_time_prepare_emi.setAlignment(QtCore.Qt.AlignCenter)
        self.label_time_prepare_emi.setObjectName("label_time_prepare_emi")
        self.horizontalLayout_3.addWidget(self.label_time_prepare_emi)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(200, 0))
        self.label_4.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.progressBar_recTOsou = QtWidgets.QProgressBar(self.verticalLayoutWidget)
        self.progressBar_recTOsou.setProperty("value", 0)
        self.progressBar_recTOsou.setObjectName("progressBar_recTOsou")
        self.horizontalLayout_5.addWidget(self.progressBar_recTOsou)
        self.label_time_recTOsou = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_time_recTOsou.sizePolicy().hasHeightForWidth())
        self.label_time_recTOsou.setSizePolicy(sizePolicy)
        self.label_time_recTOsou.setMinimumSize(QtCore.QSize(200, 0))
        self.label_time_recTOsou.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_time_recTOsou.setAlignment(QtCore.Qt.AlignCenter)
        self.label_time_recTOsou.setObjectName("label_time_recTOsou")
        self.horizontalLayout_5.addWidget(self.label_time_recTOsou)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(200, 0))
        self.label_5.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.progressBar_difTOsou = QtWidgets.QProgressBar(self.verticalLayoutWidget)
        self.progressBar_difTOsou.setProperty("value", 0)
        self.progressBar_difTOsou.setObjectName("progressBar_difTOsou")
        self.horizontalLayout_6.addWidget(self.progressBar_difTOsou)
        self.label_time_difTOsou = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_time_difTOsou.sizePolicy().hasHeightForWidth())
        self.label_time_difTOsou.setSizePolicy(sizePolicy)
        self.label_time_difTOsou.setMinimumSize(QtCore.QSize(200, 0))
        self.label_time_difTOsou.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_time_difTOsou.setAlignment(QtCore.Qt.AlignCenter)
        self.label_time_difTOsou.setObjectName("label_time_difTOsou")
        self.horizontalLayout_6.addWidget(self.label_time_difTOsou)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(200, 0))
        self.label_6.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.progressBar_recTOdif = QtWidgets.QProgressBar(self.verticalLayoutWidget)
        self.progressBar_recTOdif.setProperty("value", 0)
        self.progressBar_recTOdif.setObjectName("progressBar_recTOdif")
        self.horizontalLayout_7.addWidget(self.progressBar_recTOdif)
        self.label_time_recTOdif = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_time_recTOdif.sizePolicy().hasHeightForWidth())
        self.label_time_recTOdif.setSizePolicy(sizePolicy)
        self.label_time_recTOdif.setMinimumSize(QtCore.QSize(200, 0))
        self.label_time_recTOdif.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_time_recTOdif.setAlignment(QtCore.Qt.AlignCenter)
        self.label_time_recTOdif.setObjectName("label_time_recTOdif")
        self.horizontalLayout_7.addWidget(self.label_time_recTOdif)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_calculate = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_calculate.sizePolicy().hasHeightForWidth())
        self.label_calculate.setSizePolicy(sizePolicy)
        self.label_calculate.setMinimumSize(QtCore.QSize(200, 0))
        self.label_calculate.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_calculate.setAlignment(QtCore.Qt.AlignCenter)
        self.label_calculate.setObjectName("label_calculate")
        self.horizontalLayout_8.addWidget(self.label_calculate)
        self.progressBar_calculate = QtWidgets.QProgressBar(self.verticalLayoutWidget)
        self.progressBar_calculate.setProperty("value", 0)
        self.progressBar_calculate.setObjectName("progressBar_calculate")
        self.horizontalLayout_8.addWidget(self.progressBar_calculate)
        self.label_time_calculate = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_time_calculate.sizePolicy().hasHeightForWidth())
        self.label_time_calculate.setSizePolicy(sizePolicy)
        self.label_time_calculate.setMinimumSize(QtCore.QSize(200, 0))
        self.label_time_calculate.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_time_calculate.setAlignment(QtCore.Qt.AlignCenter)
        self.label_time_calculate.setObjectName("label_time_calculate")
        self.horizontalLayout_8.addWidget(self.label_time_calculate)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.label_time_start = QtWidgets.QLabel(self.tabCalculate)
        self.label_time_start.setGeometry(QtCore.QRect(504, 42, 300, 17))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_time_start.sizePolicy().hasHeightForWidth())
        self.label_time_start.setSizePolicy(sizePolicy)
        self.label_time_start.setMinimumSize(QtCore.QSize(300, 0))
        self.label_time_start.setMaximumSize(QtCore.QSize(300, 16777215))
        self.label_time_start.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_time_start.setObjectName("label_time_start")
        self.label_time_end = QtWidgets.QLabel(self.tabCalculate)
        self.label_time_end.setGeometry(QtCore.QRect(504, 62, 300, 17))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_time_end.sizePolicy().hasHeightForWidth())
        self.label_time_end.setSizePolicy(sizePolicy)
        self.label_time_end.setMinimumSize(QtCore.QSize(300, 0))
        self.label_time_end.setMaximumSize(QtCore.QSize(300, 16777215))
        self.label_time_end.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_time_end.setObjectName("label_time_end")
        self.label_time_duration = QtWidgets.QLabel(self.tabCalculate)
        self.label_time_duration.setGeometry(QtCore.QRect(504, 82, 300, 17))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_time_duration.sizePolicy().hasHeightForWidth())
        self.label_time_duration.setSizePolicy(sizePolicy)
        self.label_time_duration.setMinimumSize(QtCore.QSize(300, 0))
        self.label_time_duration.setMaximumSize(QtCore.QSize(300, 16777215))
        self.label_time_duration.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_time_duration.setObjectName("label_time_duration")
        self.tabWidget.addTab(self.tabCalculate, "")

        self.retranslateUi(CalculateNoiseLevels_window)
        self.tabWidget.setCurrentIndex(1)
        self.buttonBox.accepted.connect(CalculateNoiseLevels_window.accept)
        self.buttonBox.rejected.connect(CalculateNoiseLevels_window.reject)
        QtCore.QMetaObject.connectSlotsByName(CalculateNoiseLevels_window)

    def retranslateUi(self, CalculateNoiseLevels_window):
        _translate = QtCore.QCoreApplication.translate
        CalculateNoiseLevels_window.setWindowTitle(_translate("CalculateNoiseLevels_window", "Calculate Noise Levels"))
        self.label_8.setText(_translate("CalculateNoiseLevels_window", "This script calculates the noise levels. "))
        self.reload_last_settings_pushButton.setText(_translate("CalculateNoiseLevels_window", "Reload last Settings"))
        self.label_9.setText(_translate("CalculateNoiseLevels_window", "Otherwise you can reload the last or a saved Setting file:"))
        self.reload_saved_settings_pushButton.setText(_translate("CalculateNoiseLevels_window", "Reload a saved Settings file"))
        self.label_10.setText(_translate("CalculateNoiseLevels_window", "Compile the next sections to calculate the levels:"))
        self.label_11.setText(_translate("CalculateNoiseLevels_window", "1. INPUT: Insert the receivers, sources and buildings layers."))
        self.label_12.setText(_translate("CalculateNoiseLevels_window", "2. OPTIONS: Select some option settings as the research distance."))
        self.label_13.setText(_translate("CalculateNoiseLevels_window", "3. CALCULATE: Calculate the levels to the receivers."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("CalculateNoiseLevels_window", "Start"))
        self.receivers_layer_title.setText(_translate("CalculateNoiseLevels_window", "RECEIVERS"))
        self.receivers_layer_label.setText(_translate("CalculateNoiseLevels_window", "Choose a point layer as receiver"))
        self.sources_layer_title.setText(_translate("CalculateNoiseLevels_window", "SOURCES"))
        self.sources_pts_layer_checkBox.setText(_translate("CalculateNoiseLevels_window", "POINTS"))
        self.sources_pts_layer_label.setText(_translate("CalculateNoiseLevels_window", "Choose a point layer as source"))
        self.sources_pts_pushButton.setText(_translate("CalculateNoiseLevels_window", "Details"))
        self.sources_roads_layer_checkBox.setText(_translate("CalculateNoiseLevels_window", "ROADS"))
        self.sources_roads_layer_label.setText(_translate("CalculateNoiseLevels_window", "Choose a line layer as source"))
        self.sources_roads_pushButton.setText(_translate("CalculateNoiseLevels_window", "Details"))
        self.buildings_layer_checkBox.setText(_translate("CalculateNoiseLevels_window", "BUILDINGS"))
        self.buildings_layer_label.setText(_translate("CalculateNoiseLevels_window", "Choose a polygon layer as buildings"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabGeometry), _translate("CalculateNoiseLevels_window", "Input"))
        self.research_ray_label.setText(_translate("CalculateNoiseLevels_window", "Research ray (m)"))
        self.L_den_checkBox.setText(_translate("CalculateNoiseLevels_window", " L den  calculation"))
        self.L_den_hours_label.setText(_translate("CalculateNoiseLevels_window", "Total hours"))
        self.L_den_penalty_label.setText(_translate("CalculateNoiseLevels_window", "Penalizations (dB)"))
        self.L_den_day_label.setText(_translate("CalculateNoiseLevels_window", "L day"))
        self.L_den_nig_label.setText(_translate("CalculateNoiseLevels_window", "L nig"))
        self.L_den_eve_label.setText(_translate("CalculateNoiseLevels_window", "L eve"))
        self.save_settings_checkBox.setText(_translate("CalculateNoiseLevels_window", "Save current Settings in a xml file"))
        self.save_settings_pushButton.setText(_translate("CalculateNoiseLevels_window", "Browse"))
        self.research_ray_label_2.setText(_translate("CalculateNoiseLevels_window", "Temperature (Celsius degree)"))
        self.research_ray_label_3.setText(_translate("CalculateNoiseLevels_window", "Relative humidity (%)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabOptions), _translate("CalculateNoiseLevels_window", "Options"))
        self.label_14.setText(_translate("CalculateNoiseLevels_window", "Create the sound rays layers if you want to control the single noise level contribution."))
        self.diff_rays_layer_checkBox.setText(_translate("CalculateNoiseLevels_window", "Create diffraction sound rays layer (output line layer)"))
        self.diff_rays_layer_pushButton.setText(_translate("CalculateNoiseLevels_window", "Browse"))
        self.rays_layer_checkBox.setText(_translate("CalculateNoiseLevels_window", "Create direct sound rays layer (output line layer)"))
        self.rays_layer_pushButton.setText(_translate("CalculateNoiseLevels_window", "Browse"))
        self.label_15.setText(_translate("CalculateNoiseLevels_window", "This operation can take a long time, select the rays creation only for little calculations."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDebug), _translate("CalculateNoiseLevels_window", "Debug"))
        self.calculate_pushButton.setText(_translate("CalculateNoiseLevels_window", "CALCULATE"))
        self.label.setText(_translate("CalculateNoiseLevels_window", "Create diffraction points"))
        self.label_time_create_dif.setText(_translate("CalculateNoiseLevels_window", "Done in HH:MM:SS.sss"))
        self.label_2.setText(_translate("CalculateNoiseLevels_window", "Prepare emission points"))
        self.label_time_prepare_emi.setText(_translate("CalculateNoiseLevels_window", "Done in HH:MM:SS.sss"))
        self.label_4.setText(_translate("CalculateNoiseLevels_window", "Find receivers-sources rays"))
        self.label_time_recTOsou.setText(_translate("CalculateNoiseLevels_window", "Done in HH:MM:SS.sss"))
        self.label_5.setText(_translate("CalculateNoiseLevels_window", "Find diffractors-sources rays"))
        self.label_time_difTOsou.setText(_translate("CalculateNoiseLevels_window", "Done in HH:MM:SS.sss"))
        self.label_6.setText(_translate("CalculateNoiseLevels_window", "Find receivers-diffractors rays"))
        self.label_time_recTOdif.setText(_translate("CalculateNoiseLevels_window", "Done in HH:MM:SS.sss"))
        self.label_calculate.setText(_translate("CalculateNoiseLevels_window", "Calculate levels"))
        self.label_time_calculate.setText(_translate("CalculateNoiseLevels_window", "Done in HH:MM:SS.sss"))
        self.label_time_start.setText(_translate("CalculateNoiseLevels_window", "Done in HH:MM:SS.sss"))
        self.label_time_end.setText(_translate("CalculateNoiseLevels_window", "Done in HH:MM:SS.sss"))
        self.label_time_duration.setText(_translate("CalculateNoiseLevels_window", "Done in HH:MM:SS.sss"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCalculate), _translate("CalculateNoiseLevels_window", "Calculate"))

