# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_CalculateNoiseLevels.ui'
#
# Created: Wed Sep 17 15:42:24 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CalculateNoiseLevels_window(object):
    def setupUi(self, CalculateNoiseLevels_window):
        CalculateNoiseLevels_window.setObjectName(_fromUtf8("CalculateNoiseLevels_window"))
        CalculateNoiseLevels_window.resize(852, 499)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CalculateNoiseLevels_window.sizePolicy().hasHeightForWidth())
        CalculateNoiseLevels_window.setSizePolicy(sizePolicy)
        CalculateNoiseLevels_window.setMinimumSize(QtCore.QSize(852, 499))
        CalculateNoiseLevels_window.setMaximumSize(QtCore.QSize(852, 499))
        self.scrollArea_2 = QtGui.QScrollArea(CalculateNoiseLevels_window)
        self.scrollArea_2.setGeometry(QtCore.QRect(20, 20, 811, 411))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, -459, 793, 1018))
        self.scrollAreaWidgetContents_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.frame = QtGui.QFrame(self.scrollAreaWidgetContents_2)
        self.frame.setMinimumSize(QtCore.QSize(700, 1000))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.L_gen_h_s_comboBox = QtGui.QComboBox(self.frame)
        self.L_gen_h_s_comboBox.setGeometry(QtCore.QRect(210, 365, 131, 27))
        self.L_gen_h_s_comboBox.setObjectName(_fromUtf8("L_gen_h_s_comboBox"))
        self.power_radioButton = QtGui.QRadioButton(self.frame)
        self.power_radioButton.setGeometry(QtCore.QRect(310, 175, 221, 22))
        self.power_radioButton.setObjectName(_fromUtf8("power_radioButton"))
        self.slope_comboBox = QtGui.QComboBox(self.frame)
        self.slope_comboBox.setGeometry(QtCore.QRect(450, 215, 131, 27))
        self.slope_comboBox.setObjectName(_fromUtf8("slope_comboBox"))
        self.L_gen_h_n_comboBox = QtGui.QComboBox(self.frame)
        self.L_gen_h_n_comboBox.setGeometry(QtCore.QRect(210, 305, 131, 27))
        self.L_gen_h_n_comboBox.setObjectName(_fromUtf8("L_gen_h_n_comboBox"))
        self.L_eve_type_comboBox = QtGui.QComboBox(self.frame)
        self.L_eve_type_comboBox.setGeometry(QtCore.QRect(490, 395, 131, 27))
        self.L_eve_type_comboBox.setObjectName(_fromUtf8("L_eve_type_comboBox"))
        self.type_label = QtGui.QLabel(self.frame)
        self.type_label.setGeometry(QtCore.QRect(10, 400, 189, 17))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.type_label.sizePolicy().hasHeightForWidth())
        self.type_label.setSizePolicy(sizePolicy)
        self.type_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.type_label.setObjectName(_fromUtf8("type_label"))
        self.L_gen_p_checkBox = QtGui.QCheckBox(self.frame)
        self.L_gen_p_checkBox.setGeometry(QtCore.QRect(210, 435, 131, 22))
        self.L_gen_p_checkBox.setChecked(True)
        self.L_gen_p_checkBox.setObjectName(_fromUtf8("L_gen_p_checkBox"))
        self.L_gen_v_checkBox = QtGui.QCheckBox(self.frame)
        self.L_gen_v_checkBox.setGeometry(QtCore.QRect(210, 250, 131, 22))
        self.L_gen_v_checkBox.setChecked(True)
        self.L_gen_v_checkBox.setObjectName(_fromUtf8("L_gen_v_checkBox"))
        self.L_day_l_s_comboBox = QtGui.QComboBox(self.frame)
        self.L_day_l_s_comboBox.setGeometry(QtCore.QRect(350, 335, 131, 27))
        self.L_day_l_s_comboBox.setObjectName(_fromUtf8("L_day_l_s_comboBox"))
        self.line_3 = QtGui.QFrame(self.frame)
        self.line_3.setGeometry(QtCore.QRect(10, 755, 751, 20))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.v_l_label = QtGui.QLabel(self.frame)
        self.v_l_label.setGeometry(QtCore.QRect(10, 340, 189, 17))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.v_l_label.sizePolicy().hasHeightForWidth())
        self.v_l_label.setSizePolicy(sizePolicy)
        self.v_l_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.v_l_label.setObjectName(_fromUtf8("v_l_label"))
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.frame)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 830, 751, 61))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.source_points_layer_verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.source_points_layer_verticalLayout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.source_points_layer_verticalLayout.setMargin(0)
        self.source_points_layer_verticalLayout.setObjectName(_fromUtf8("source_points_layer_verticalLayout"))
        self.emission_points_layer_checkBox = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        self.emission_points_layer_checkBox.setEnabled(True)
        self.emission_points_layer_checkBox.setChecked(False)
        self.emission_points_layer_checkBox.setObjectName(_fromUtf8("emission_points_layer_checkBox"))
        self.source_points_layer_verticalLayout.addWidget(self.emission_points_layer_checkBox)
        self.receiver_layer_horizontalLayout = QtGui.QHBoxLayout()
        self.receiver_layer_horizontalLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.receiver_layer_horizontalLayout.setObjectName(_fromUtf8("receiver_layer_horizontalLayout"))
        self.emission_points_layer_lineEdit = QtGui.QLineEdit(self.verticalLayoutWidget_3)
        self.emission_points_layer_lineEdit.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.emission_points_layer_lineEdit.sizePolicy().hasHeightForWidth())
        self.emission_points_layer_lineEdit.setSizePolicy(sizePolicy)
        self.emission_points_layer_lineEdit.setObjectName(_fromUtf8("emission_points_layer_lineEdit"))
        self.receiver_layer_horizontalLayout.addWidget(self.emission_points_layer_lineEdit)
        self.emission_points_layer_pushButton = QtGui.QPushButton(self.verticalLayoutWidget_3)
        self.emission_points_layer_pushButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.emission_points_layer_pushButton.sizePolicy().hasHeightForWidth())
        self.emission_points_layer_pushButton.setSizePolicy(sizePolicy)
        self.emission_points_layer_pushButton.setObjectName(_fromUtf8("emission_points_layer_pushButton"))
        self.receiver_layer_horizontalLayout.addWidget(self.emission_points_layer_pushButton)
        self.source_points_layer_verticalLayout.addLayout(self.receiver_layer_horizontalLayout)
        self.n_l_label = QtGui.QLabel(self.frame)
        self.n_l_label.setGeometry(QtCore.QRect(10, 280, 189, 17))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.n_l_label.sizePolicy().hasHeightForWidth())
        self.n_l_label.setSizePolicy(sizePolicy)
        self.n_l_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.n_l_label.setObjectName(_fromUtf8("n_l_label"))
        self.slope_label = QtGui.QLabel(self.frame)
        self.slope_label.setGeometry(QtCore.QRect(350, 220, 91, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slope_label.sizePolicy().hasHeightForWidth())
        self.slope_label.setSizePolicy(sizePolicy)
        self.slope_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.slope_label.setObjectName(_fromUtf8("slope_label"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.frame)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 105, 751, 61))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.roads_layer_verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.roads_layer_verticalLayout.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.roads_layer_verticalLayout.setMargin(0)
        self.roads_layer_verticalLayout.setObjectName(_fromUtf8("roads_layer_verticalLayout"))
        self.roads_layer_label = QtGui.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.roads_layer_label.sizePolicy().hasHeightForWidth())
        self.roads_layer_label.setSizePolicy(sizePolicy)
        self.roads_layer_label.setObjectName(_fromUtf8("roads_layer_label"))
        self.roads_layer_verticalLayout.addWidget(self.roads_layer_label)
        self.roads_layer_comboBox = QtGui.QComboBox(self.verticalLayoutWidget_2)
        self.roads_layer_comboBox.setObjectName(_fromUtf8("roads_layer_comboBox"))
        self.roads_layer_verticalLayout.addWidget(self.roads_layer_comboBox)
        self.L_gen_p_comboBox = QtGui.QComboBox(self.frame)
        self.L_gen_p_comboBox.setGeometry(QtCore.QRect(210, 460, 131, 27))
        self.L_gen_p_comboBox.setObjectName(_fromUtf8("L_gen_p_comboBox"))
        self.L_eve_p_checkBox = QtGui.QCheckBox(self.frame)
        self.L_eve_p_checkBox.setGeometry(QtCore.QRect(490, 435, 131, 22))
        self.L_eve_p_checkBox.setChecked(False)
        self.L_eve_p_checkBox.setObjectName(_fromUtf8("L_eve_p_checkBox"))
        self.line_4 = QtGui.QFrame(self.frame)
        self.line_4.setGeometry(QtCore.QRect(10, 660, 751, 20))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.research_ray_comboBox = QtGui.QComboBox(self.frame)
        self.research_ray_comboBox.setGeometry(QtCore.QRect(210, 520, 131, 27))
        self.research_ray_comboBox.setObjectName(_fromUtf8("research_ray_comboBox"))
        self.research_ray_label = QtGui.QLabel(self.frame)
        self.research_ray_label.setGeometry(QtCore.QRect(10, 525, 189, 17))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.research_ray_label.sizePolicy().hasHeightForWidth())
        self.research_ray_label.setSizePolicy(sizePolicy)
        self.research_ray_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.research_ray_label.setObjectName(_fromUtf8("research_ray_label"))
        self.L_gen_type_comboBox = QtGui.QComboBox(self.frame)
        self.L_gen_type_comboBox.setGeometry(QtCore.QRect(210, 395, 131, 27))
        self.L_gen_type_comboBox.setObjectName(_fromUtf8("L_gen_type_comboBox"))
        self.L_gen_l_s_comboBox = QtGui.QComboBox(self.frame)
        self.L_gen_l_s_comboBox.setGeometry(QtCore.QRect(210, 335, 131, 27))
        self.L_gen_l_s_comboBox.setObjectName(_fromUtf8("L_gen_l_s_comboBox"))
        self.L_den_checkBox = QtGui.QCheckBox(self.frame)
        self.L_den_checkBox.setGeometry(QtCore.QRect(123, 560, 101, 20))
        self.L_den_checkBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.L_den_checkBox.setChecked(False)
        self.L_den_checkBox.setObjectName(_fromUtf8("L_den_checkBox"))
        self.v_p_label = QtGui.QLabel(self.frame)
        self.v_p_label.setGeometry(QtCore.QRect(10, 370, 189, 17))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.v_p_label.sizePolicy().hasHeightForWidth())
        self.v_p_label.setSizePolicy(sizePolicy)
        self.v_p_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.v_p_label.setObjectName(_fromUtf8("v_p_label"))
        self.L_day_l_n_comboBox = QtGui.QComboBox(self.frame)
        self.L_day_l_n_comboBox.setGeometry(QtCore.QRect(350, 275, 131, 27))
        self.L_day_l_n_comboBox.setObjectName(_fromUtf8("L_day_l_n_comboBox"))
        self.L_day_v_checkBox = QtGui.QCheckBox(self.frame)
        self.L_day_v_checkBox.setGeometry(QtCore.QRect(350, 250, 131, 22))
        self.L_day_v_checkBox.setChecked(False)
        self.L_day_v_checkBox.setObjectName(_fromUtf8("L_day_v_checkBox"))
        self.L_eve_v_checkBox = QtGui.QCheckBox(self.frame)
        self.L_eve_v_checkBox.setGeometry(QtCore.QRect(490, 250, 131, 22))
        self.L_eve_v_checkBox.setChecked(False)
        self.L_eve_v_checkBox.setObjectName(_fromUtf8("L_eve_v_checkBox"))
        self.L_day_h_n_comboBox = QtGui.QComboBox(self.frame)
        self.L_day_h_n_comboBox.setGeometry(QtCore.QRect(350, 305, 131, 27))
        self.L_day_h_n_comboBox.setObjectName(_fromUtf8("L_day_h_n_comboBox"))
        self.power_label = QtGui.QLabel(self.frame)
        self.power_label.setGeometry(QtCore.QRect(10, 465, 189, 17))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.power_label.sizePolicy().hasHeightForWidth())
        self.power_label.setSizePolicy(sizePolicy)
        self.power_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.power_label.setObjectName(_fromUtf8("power_label"))
        self.L_day_p_comboBox = QtGui.QComboBox(self.frame)
        self.L_day_p_comboBox.setGeometry(QtCore.QRect(350, 460, 131, 27))
        self.L_day_p_comboBox.setObjectName(_fromUtf8("L_day_p_comboBox"))
        self.L_gen_l_n_comboBox = QtGui.QComboBox(self.frame)
        self.L_gen_l_n_comboBox.setGeometry(QtCore.QRect(210, 275, 131, 27))
        self.L_gen_l_n_comboBox.setObjectName(_fromUtf8("L_gen_l_n_comboBox"))
        self.L_eve_l_s_comboBox = QtGui.QComboBox(self.frame)
        self.L_eve_l_s_comboBox.setGeometry(QtCore.QRect(490, 335, 131, 27))
        self.L_eve_l_s_comboBox.setObjectName(_fromUtf8("L_eve_l_s_comboBox"))
        self.L_eve_h_s_comboBox = QtGui.QComboBox(self.frame)
        self.L_eve_h_s_comboBox.setGeometry(QtCore.QRect(490, 365, 131, 27))
        self.L_eve_h_s_comboBox.setObjectName(_fromUtf8("L_eve_h_s_comboBox"))
        self.n_p_label = QtGui.QLabel(self.frame)
        self.n_p_label.setGeometry(QtCore.QRect(10, 310, 189, 17))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.n_p_label.sizePolicy().hasHeightForWidth())
        self.n_p_label.setSizePolicy(sizePolicy)
        self.n_p_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.n_p_label.setObjectName(_fromUtf8("n_p_label"))
        self.verticalLayoutWidget_5 = QtGui.QWidget(self.frame)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(10, 900, 751, 61))
        self.verticalLayoutWidget_5.setObjectName(_fromUtf8("verticalLayoutWidget_5"))
        self.rays_layer_verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget_5)
        self.rays_layer_verticalLayout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.rays_layer_verticalLayout.setMargin(0)
        self.rays_layer_verticalLayout.setObjectName(_fromUtf8("rays_layer_verticalLayout"))
        self.rays_layer_checkBox = QtGui.QCheckBox(self.verticalLayoutWidget_5)
        self.rays_layer_checkBox.setEnabled(True)
        self.rays_layer_checkBox.setChecked(False)
        self.rays_layer_checkBox.setObjectName(_fromUtf8("rays_layer_checkBox"))
        self.rays_layer_verticalLayout.addWidget(self.rays_layer_checkBox)
        self.receiver_layer_horizontalLayout_2 = QtGui.QHBoxLayout()
        self.receiver_layer_horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.receiver_layer_horizontalLayout_2.setObjectName(_fromUtf8("receiver_layer_horizontalLayout_2"))
        self.rays_layer_lineEdit = QtGui.QLineEdit(self.verticalLayoutWidget_5)
        self.rays_layer_lineEdit.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rays_layer_lineEdit.sizePolicy().hasHeightForWidth())
        self.rays_layer_lineEdit.setSizePolicy(sizePolicy)
        self.rays_layer_lineEdit.setObjectName(_fromUtf8("rays_layer_lineEdit"))
        self.receiver_layer_horizontalLayout_2.addWidget(self.rays_layer_lineEdit)
        self.rays_layer_pushButton = QtGui.QPushButton(self.verticalLayoutWidget_5)
        self.rays_layer_pushButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rays_layer_pushButton.sizePolicy().hasHeightForWidth())
        self.rays_layer_pushButton.setSizePolicy(sizePolicy)
        self.rays_layer_pushButton.setObjectName(_fromUtf8("rays_layer_pushButton"))
        self.receiver_layer_horizontalLayout_2.addWidget(self.rays_layer_pushButton)
        self.rays_layer_verticalLayout.addLayout(self.receiver_layer_horizontalLayout_2)
        self.L_eve_h_n_comboBox = QtGui.QComboBox(self.frame)
        self.L_eve_h_n_comboBox.setGeometry(QtCore.QRect(490, 305, 131, 27))
        self.L_eve_h_n_comboBox.setObjectName(_fromUtf8("L_eve_h_n_comboBox"))
        self.L_day_h_s_comboBox = QtGui.QComboBox(self.frame)
        self.L_day_h_s_comboBox.setGeometry(QtCore.QRect(350, 365, 131, 27))
        self.L_day_h_s_comboBox.setObjectName(_fromUtf8("L_day_h_s_comboBox"))
        self.line_2 = QtGui.QFrame(self.frame)
        self.line_2.setGeometry(QtCore.QRect(10, 495, 751, 20))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.line = QtGui.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(7, 85, 751, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.L_eve_p_comboBox = QtGui.QComboBox(self.frame)
        self.L_eve_p_comboBox.setGeometry(QtCore.QRect(490, 460, 131, 27))
        self.L_eve_p_comboBox.setObjectName(_fromUtf8("L_eve_p_comboBox"))
        self.verticalLayoutWidget = QtGui.QWidget(self.frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 15, 751, 61))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.receivers_layer_verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.receivers_layer_verticalLayout.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.receivers_layer_verticalLayout.setMargin(0)
        self.receivers_layer_verticalLayout.setObjectName(_fromUtf8("receivers_layer_verticalLayout"))
        self.receiver_points_layer_label = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.receiver_points_layer_label.sizePolicy().hasHeightForWidth())
        self.receiver_points_layer_label.setSizePolicy(sizePolicy)
        self.receiver_points_layer_label.setObjectName(_fromUtf8("receiver_points_layer_label"))
        self.receivers_layer_verticalLayout.addWidget(self.receiver_points_layer_label)
        self.receiver_points_layer_comboBox = QtGui.QComboBox(self.verticalLayoutWidget)
        self.receiver_points_layer_comboBox.setObjectName(_fromUtf8("receiver_points_layer_comboBox"))
        self.receivers_layer_verticalLayout.addWidget(self.receiver_points_layer_comboBox)
        self.surface_comboBox = QtGui.QComboBox(self.frame)
        self.surface_comboBox.setGeometry(QtCore.QRect(210, 215, 131, 27))
        self.surface_comboBox.setObjectName(_fromUtf8("surface_comboBox"))
        self.L_eve_l_n_comboBox = QtGui.QComboBox(self.frame)
        self.L_eve_l_n_comboBox.setGeometry(QtCore.QRect(490, 275, 131, 27))
        self.L_eve_l_n_comboBox.setObjectName(_fromUtf8("L_eve_l_n_comboBox"))
        self.vehicles_radioButton = QtGui.QRadioButton(self.frame)
        self.vehicles_radioButton.setGeometry(QtCore.QRect(210, 175, 116, 22))
        self.vehicles_radioButton.setChecked(True)
        self.vehicles_radioButton.setObjectName(_fromUtf8("vehicles_radioButton"))
        self.verticalLayoutWidget_4 = QtGui.QWidget(self.frame)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 680, 751, 61))
        self.verticalLayoutWidget_4.setObjectName(_fromUtf8("verticalLayoutWidget_4"))
        self.obstacles_layer_verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget_4)
        self.obstacles_layer_verticalLayout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.obstacles_layer_verticalLayout.setMargin(0)
        self.obstacles_layer_verticalLayout.setObjectName(_fromUtf8("obstacles_layer_verticalLayout"))
        self.obstacles_layer_checkBox = QtGui.QCheckBox(self.verticalLayoutWidget_4)
        self.obstacles_layer_checkBox.setEnabled(True)
        self.obstacles_layer_checkBox.setChecked(False)
        self.obstacles_layer_checkBox.setObjectName(_fromUtf8("obstacles_layer_checkBox"))
        self.obstacles_layer_verticalLayout.addWidget(self.obstacles_layer_checkBox)
        self.obstacles_layer_comboBox = QtGui.QComboBox(self.verticalLayoutWidget_4)
        self.obstacles_layer_comboBox.setEnabled(False)
        self.obstacles_layer_comboBox.setObjectName(_fromUtf8("obstacles_layer_comboBox"))
        self.obstacles_layer_verticalLayout.addWidget(self.obstacles_layer_comboBox)
        self.L_day_type_comboBox = QtGui.QComboBox(self.frame)
        self.L_day_type_comboBox.setGeometry(QtCore.QRect(350, 395, 131, 27))
        self.L_day_type_comboBox.setObjectName(_fromUtf8("L_day_type_comboBox"))
        self.implementation_label = QtGui.QLabel(self.frame)
        self.implementation_label.setGeometry(QtCore.QRect(10, 178, 189, 17))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.implementation_label.sizePolicy().hasHeightForWidth())
        self.implementation_label.setSizePolicy(sizePolicy)
        self.implementation_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.implementation_label.setObjectName(_fromUtf8("implementation_label"))
        self.L_day_p_checkBox = QtGui.QCheckBox(self.frame)
        self.L_day_p_checkBox.setGeometry(QtCore.QRect(350, 435, 131, 22))
        self.L_day_p_checkBox.setChecked(False)
        self.L_day_p_checkBox.setObjectName(_fromUtf8("L_day_p_checkBox"))
        self.surface_label = QtGui.QLabel(self.frame)
        self.surface_label.setGeometry(QtCore.QRect(10, 220, 189, 17))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.surface_label.sizePolicy().hasHeightForWidth())
        self.surface_label.setSizePolicy(sizePolicy)
        self.surface_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.surface_label.setObjectName(_fromUtf8("surface_label"))
        self.note_label_2 = QtGui.QLabel(self.frame)
        self.note_label_2.setGeometry(QtCore.QRect(10, 780, 751, 41))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.note_label_2.sizePolicy().hasHeightForWidth())
        self.note_label_2.setSizePolicy(sizePolicy)
        self.note_label_2.setText(_fromUtf8("<html><head/><body><p align=\"center\"><span style=\" font-style:italic;\">Check the following boxes (and so create the emission points and rays layers)<br/></span><span style=\" font-style:italic; text-decoration: underline;\">only</span><span style=\" font-style:italic;\"> if you want to test the plugin</span></p></body></html>"))
        self.note_label_2.setObjectName(_fromUtf8("note_label_2"))
        self.L_nig_l_n_comboBox = QtGui.QComboBox(self.frame)
        self.L_nig_l_n_comboBox.setGeometry(QtCore.QRect(630, 275, 131, 27))
        self.L_nig_l_n_comboBox.setObjectName(_fromUtf8("L_nig_l_n_comboBox"))
        self.L_nig_h_n_comboBox = QtGui.QComboBox(self.frame)
        self.L_nig_h_n_comboBox.setGeometry(QtCore.QRect(630, 305, 131, 27))
        self.L_nig_h_n_comboBox.setObjectName(_fromUtf8("L_nig_h_n_comboBox"))
        self.L_nig_v_checkBox = QtGui.QCheckBox(self.frame)
        self.L_nig_v_checkBox.setGeometry(QtCore.QRect(630, 250, 131, 22))
        self.L_nig_v_checkBox.setChecked(False)
        self.L_nig_v_checkBox.setObjectName(_fromUtf8("L_nig_v_checkBox"))
        self.L_nig_type_comboBox = QtGui.QComboBox(self.frame)
        self.L_nig_type_comboBox.setGeometry(QtCore.QRect(630, 395, 131, 27))
        self.L_nig_type_comboBox.setObjectName(_fromUtf8("L_nig_type_comboBox"))
        self.L_nig_h_s_comboBox = QtGui.QComboBox(self.frame)
        self.L_nig_h_s_comboBox.setGeometry(QtCore.QRect(630, 365, 131, 27))
        self.L_nig_h_s_comboBox.setObjectName(_fromUtf8("L_nig_h_s_comboBox"))
        self.L_nig_p_checkBox = QtGui.QCheckBox(self.frame)
        self.L_nig_p_checkBox.setGeometry(QtCore.QRect(630, 435, 131, 22))
        self.L_nig_p_checkBox.setChecked(False)
        self.L_nig_p_checkBox.setObjectName(_fromUtf8("L_nig_p_checkBox"))
        self.L_nig_p_comboBox = QtGui.QComboBox(self.frame)
        self.L_nig_p_comboBox.setGeometry(QtCore.QRect(630, 460, 131, 27))
        self.L_nig_p_comboBox.setObjectName(_fromUtf8("L_nig_p_comboBox"))
        self.L_nig_l_s_comboBox = QtGui.QComboBox(self.frame)
        self.L_nig_l_s_comboBox.setGeometry(QtCore.QRect(630, 335, 131, 27))
        self.L_nig_l_s_comboBox.setObjectName(_fromUtf8("L_nig_l_s_comboBox"))
        self.L_day_hours_spinBox = QtGui.QSpinBox(self.frame)
        self.L_day_hours_spinBox.setGeometry(QtCore.QRect(280, 580, 51, 22))
        self.L_day_hours_spinBox.setMaximum(24)
        self.L_day_hours_spinBox.setProperty("value", 14)
        self.L_day_hours_spinBox.setObjectName(_fromUtf8("L_day_hours_spinBox"))
        self.L_den_hours_label = QtGui.QLabel(self.frame)
        self.L_den_hours_label.setGeometry(QtCore.QRect(267, 560, 91, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.L_den_hours_label.sizePolicy().hasHeightForWidth())
        self.L_den_hours_label.setSizePolicy(sizePolicy)
        self.L_den_hours_label.setObjectName(_fromUtf8("L_den_hours_label"))
        self.L_den_penalty_label = QtGui.QLabel(self.frame)
        self.L_den_penalty_label.setGeometry(QtCore.QRect(362, 560, 111, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.L_den_penalty_label.sizePolicy().hasHeightForWidth())
        self.L_den_penalty_label.setSizePolicy(sizePolicy)
        self.L_den_penalty_label.setObjectName(_fromUtf8("L_den_penalty_label"))
        self.L_day_penalty_spinBox = QtGui.QSpinBox(self.frame)
        self.L_day_penalty_spinBox.setGeometry(QtCore.QRect(380, 580, 51, 22))
        self.L_day_penalty_spinBox.setMinimum(-99)
        self.L_day_penalty_spinBox.setObjectName(_fromUtf8("L_day_penalty_spinBox"))
        self.L_den_day_label = QtGui.QLabel(self.frame)
        self.L_den_day_label.setGeometry(QtCore.QRect(206, 580, 61, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.L_den_day_label.sizePolicy().hasHeightForWidth())
        self.L_den_day_label.setSizePolicy(sizePolicy)
        self.L_den_day_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.L_den_day_label.setObjectName(_fromUtf8("L_den_day_label"))
        self.L_den_eve_label = QtGui.QLabel(self.frame)
        self.L_den_eve_label.setGeometry(QtCore.QRect(206, 606, 61, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.L_den_eve_label.sizePolicy().hasHeightForWidth())
        self.L_den_eve_label.setSizePolicy(sizePolicy)
        self.L_den_eve_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.L_den_eve_label.setObjectName(_fromUtf8("L_den_eve_label"))
        self.L_eve_penalty_spinBox = QtGui.QSpinBox(self.frame)
        self.L_eve_penalty_spinBox.setGeometry(QtCore.QRect(380, 605, 51, 22))
        self.L_eve_penalty_spinBox.setMinimum(-99)
        self.L_eve_penalty_spinBox.setProperty("value", 5)
        self.L_eve_penalty_spinBox.setObjectName(_fromUtf8("L_eve_penalty_spinBox"))
        self.L_eve_hours_spinBox = QtGui.QSpinBox(self.frame)
        self.L_eve_hours_spinBox.setGeometry(QtCore.QRect(280, 605, 51, 22))
        self.L_eve_hours_spinBox.setMaximum(24)
        self.L_eve_hours_spinBox.setProperty("value", 2)
        self.L_eve_hours_spinBox.setObjectName(_fromUtf8("L_eve_hours_spinBox"))
        self.L_den_nig_label = QtGui.QLabel(self.frame)
        self.L_den_nig_label.setGeometry(QtCore.QRect(206, 630, 61, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.L_den_nig_label.sizePolicy().hasHeightForWidth())
        self.L_den_nig_label.setSizePolicy(sizePolicy)
        self.L_den_nig_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.L_den_nig_label.setObjectName(_fromUtf8("L_den_nig_label"))
        self.L_nig_penalty_spinBox = QtGui.QSpinBox(self.frame)
        self.L_nig_penalty_spinBox.setGeometry(QtCore.QRect(380, 630, 51, 22))
        self.L_nig_penalty_spinBox.setMinimum(-99)
        self.L_nig_penalty_spinBox.setProperty("value", 10)
        self.L_nig_penalty_spinBox.setObjectName(_fromUtf8("L_nig_penalty_spinBox"))
        self.L_nig_hours_spinBox = QtGui.QSpinBox(self.frame)
        self.L_nig_hours_spinBox.setGeometry(QtCore.QRect(280, 630, 51, 22))
        self.L_nig_hours_spinBox.setMaximum(24)
        self.L_nig_hours_spinBox.setProperty("value", 8)
        self.L_nig_hours_spinBox.setObjectName(_fromUtf8("L_nig_hours_spinBox"))
        self.verticalLayout.addWidget(self.frame)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(CalculateNoiseLevels_window)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 450, 811, 31))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.step_label = QtGui.QLabel(self.horizontalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.step_label.sizePolicy().hasHeightForWidth())
        self.step_label.setSizePolicy(sizePolicy)
        self.step_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.step_label.setObjectName(_fromUtf8("step_label"))
        self.horizontalLayout.addWidget(self.step_label)
        self.progressBar = QtGui.QProgressBar(self.horizontalLayoutWidget_2)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.horizontalLayout.addWidget(self.progressBar)
        self.run_buttonBox = QtGui.QDialogButtonBox(self.horizontalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.run_buttonBox.sizePolicy().hasHeightForWidth())
        self.run_buttonBox.setSizePolicy(sizePolicy)
        self.run_buttonBox.setFocusPolicy(QtCore.Qt.TabFocus)
        self.run_buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.run_buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.run_buttonBox.setObjectName(_fromUtf8("run_buttonBox"))
        self.horizontalLayout.addWidget(self.run_buttonBox)

        self.retranslateUi(CalculateNoiseLevels_window)
        QtCore.QObject.connect(self.run_buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), CalculateNoiseLevels_window.accept)
        QtCore.QObject.connect(self.run_buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), CalculateNoiseLevels_window.reject)
        QtCore.QMetaObject.connectSlotsByName(CalculateNoiseLevels_window)

    def retranslateUi(self, CalculateNoiseLevels_window):
        CalculateNoiseLevels_window.setWindowTitle(_translate("CalculateNoiseLevels_window", "opeNoise - Calculate Noise Levels", None))
        self.power_radioButton.setText(_translate("CalculateNoiseLevels_window", "Power levels", None))
        self.type_label.setText(_translate("CalculateNoiseLevels_window", "Road traffic type", None))
        self.L_gen_p_checkBox.setText(_translate("CalculateNoiseLevels_window", "Generic Level", None))
        self.L_gen_v_checkBox.setText(_translate("CalculateNoiseLevels_window", "Generic Level", None))
        self.v_l_label.setText(_translate("CalculateNoiseLevels_window", "Light vehicles speed (km/h)", None))
        self.emission_points_layer_checkBox.setText(_translate("CalculateNoiseLevels_window", "Emission points layer (output point layer)", None))
        self.emission_points_layer_pushButton.setText(_translate("CalculateNoiseLevels_window", "Browse", None))
        self.n_l_label.setText(_translate("CalculateNoiseLevels_window", "Light vehicles number", None))
        self.slope_label.setText(_translate("CalculateNoiseLevels_window", "Road slope", None))
        self.roads_layer_label.setText(_translate("CalculateNoiseLevels_window", "Roads layer (input line layer)", None))
        self.L_eve_p_checkBox.setText(_translate("CalculateNoiseLevels_window", "L eve", None))
        self.research_ray_label.setText(_translate("CalculateNoiseLevels_window", "Research ray (m)", None))
        self.L_den_checkBox.setText(_translate("CalculateNoiseLevels_window", " L den  ", None))
        self.v_p_label.setText(_translate("CalculateNoiseLevels_window", "Heavy vehicles speed (km/h)", None))
        self.L_day_v_checkBox.setText(_translate("CalculateNoiseLevels_window", "L day", None))
        self.L_eve_v_checkBox.setText(_translate("CalculateNoiseLevels_window", "L eve", None))
        self.power_label.setText(_translate("CalculateNoiseLevels_window", "Power levels", None))
        self.n_p_label.setText(_translate("CalculateNoiseLevels_window", "Heavy vehicles number", None))
        self.rays_layer_checkBox.setText(_translate("CalculateNoiseLevels_window", "Sound rays layer (output line layer)", None))
        self.rays_layer_pushButton.setText(_translate("CalculateNoiseLevels_window", "Browse", None))
        self.receiver_points_layer_label.setText(_translate("CalculateNoiseLevels_window", "Receiver points layer (input point layer)", None))
        self.vehicles_radioButton.setText(_translate("CalculateNoiseLevels_window", "Vehicles", None))
        self.obstacles_layer_checkBox.setText(_translate("CalculateNoiseLevels_window", "Obstacles layer (input polygon layer)", None))
        self.implementation_label.setText(_translate("CalculateNoiseLevels_window", "Implementation", None))
        self.L_day_p_checkBox.setText(_translate("CalculateNoiseLevels_window", "L day", None))
        self.surface_label.setText(_translate("CalculateNoiseLevels_window", "Road surface", None))
        self.L_nig_v_checkBox.setText(_translate("CalculateNoiseLevels_window", "L nig", None))
        self.L_nig_p_checkBox.setText(_translate("CalculateNoiseLevels_window", "L nig", None))
        self.L_den_hours_label.setText(_translate("CalculateNoiseLevels_window", "Total hours", None))
        self.L_den_penalty_label.setText(_translate("CalculateNoiseLevels_window", "Penalizations", None))
        self.L_den_day_label.setText(_translate("CalculateNoiseLevels_window", "L day", None))
        self.L_den_eve_label.setText(_translate("CalculateNoiseLevels_window", "L eve", None))
        self.L_den_nig_label.setText(_translate("CalculateNoiseLevels_window", "L nig", None))
        self.step_label.setText(_translate("CalculateNoiseLevels_window", "  STEP 1 / 2  ", None))

