# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_SourceDetailsRoads.ui'
#
# Created: Mon Nov 13 10:22:44 2017
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SourceDetailsRoads_window(object):
    def setupUi(self, SourceDetailsRoads_window):
        SourceDetailsRoads_window.setObjectName(_fromUtf8("SourceDetailsRoads_window"))
        SourceDetailsRoads_window.resize(832, 720)
        self.buttonBox = QtGui.QDialogButtonBox(SourceDetailsRoads_window)
        self.buttonBox.setGeometry(QtCore.QRect(460, 670, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayoutWidget = QtGui.QWidget(SourceDetailsRoads_window)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(150, 47, 561, 31))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_10.setMargin(0)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.POWER_R_radioButton = QtGui.QRadioButton(self.horizontalLayoutWidget)
        self.POWER_R_radioButton.setChecked(True)
        self.POWER_R_radioButton.setObjectName(_fromUtf8("POWER_R_radioButton"))
        self.horizontalLayout_10.addWidget(self.POWER_R_radioButton)
        self.NMPB_radioButton = QtGui.QRadioButton(self.horizontalLayoutWidget)
        self.NMPB_radioButton.setChecked(False)
        self.NMPB_radioButton.setObjectName(_fromUtf8("NMPB_radioButton"))
        self.horizontalLayout_10.addWidget(self.NMPB_radioButton)
        self.CNOSSOS_radioButton = QtGui.QRadioButton(self.horizontalLayoutWidget)
        self.CNOSSOS_radioButton.setChecked(False)
        self.CNOSSOS_radioButton.setObjectName(_fromUtf8("CNOSSOS_radioButton"))
        self.horizontalLayout_10.addWidget(self.CNOSSOS_radioButton)
        self.road_stackedWidget = QtGui.QStackedWidget(SourceDetailsRoads_window)
        self.road_stackedWidget.setGeometry(QtCore.QRect(9, 90, 811, 541))
        self.road_stackedWidget.setObjectName(_fromUtf8("road_stackedWidget"))
        self.road_power_page = QtGui.QWidget()
        self.road_power_page.setObjectName(_fromUtf8("road_power_page"))
        self.layoutWidget = QtGui.QWidget(self.road_power_page)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 60, 791, 35))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.n_l_label_14 = QtGui.QLabel(self.layoutWidget)
        self.n_l_label_14.setMaximumSize(QtCore.QSize(16777215, 27))
        self.n_l_label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.n_l_label_14.setObjectName(_fromUtf8("n_l_label_14"))
        self.horizontalLayout_8.addWidget(self.n_l_label_14)
        self.POWER_R_L_gen_comboBox = QtGui.QComboBox(self.layoutWidget)
        self.POWER_R_L_gen_comboBox.setMaximumSize(QtCore.QSize(16777215, 27))
        self.POWER_R_L_gen_comboBox.setObjectName(_fromUtf8("POWER_R_L_gen_comboBox"))
        self.horizontalLayout_8.addWidget(self.POWER_R_L_gen_comboBox)
        self.POWER_R_L_day_comboBox = QtGui.QComboBox(self.layoutWidget)
        self.POWER_R_L_day_comboBox.setMaximumSize(QtCore.QSize(16777215, 27))
        self.POWER_R_L_day_comboBox.setObjectName(_fromUtf8("POWER_R_L_day_comboBox"))
        self.horizontalLayout_8.addWidget(self.POWER_R_L_day_comboBox)
        self.POWER_R_L_eve_comboBox = QtGui.QComboBox(self.layoutWidget)
        self.POWER_R_L_eve_comboBox.setMaximumSize(QtCore.QSize(16777215, 27))
        self.POWER_R_L_eve_comboBox.setObjectName(_fromUtf8("POWER_R_L_eve_comboBox"))
        self.horizontalLayout_8.addWidget(self.POWER_R_L_eve_comboBox)
        self.POWER_R_L_nig_comboBox = QtGui.QComboBox(self.layoutWidget)
        self.POWER_R_L_nig_comboBox.setMaximumSize(QtCore.QSize(16777215, 27))
        self.POWER_R_L_nig_comboBox.setObjectName(_fromUtf8("POWER_R_L_nig_comboBox"))
        self.horizontalLayout_8.addWidget(self.POWER_R_L_nig_comboBox)
        self.POWER_R_L_nig_checkBox = QtGui.QCheckBox(self.road_power_page)
        self.POWER_R_L_nig_checkBox.setGeometry(QtCore.QRect(690, 20, 81, 22))
        self.POWER_R_L_nig_checkBox.setChecked(False)
        self.POWER_R_L_nig_checkBox.setObjectName(_fromUtf8("POWER_R_L_nig_checkBox"))
        self.line_10 = QtGui.QFrame(self.road_power_page)
        self.line_10.setWindowModality(QtCore.Qt.NonModal)
        self.line_10.setGeometry(QtCore.QRect(10, 40, 781, 20))
        self.line_10.setFrameShape(QtGui.QFrame.HLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.POWER_R_L_gen_checkBox = QtGui.QCheckBox(self.road_power_page)
        self.POWER_R_L_gen_checkBox.setGeometry(QtCore.QRect(210, 20, 91, 21))
        self.POWER_R_L_gen_checkBox.setChecked(True)
        self.POWER_R_L_gen_checkBox.setObjectName(_fromUtf8("POWER_R_L_gen_checkBox"))
        self.implementation_label_23 = QtGui.QLabel(self.road_power_page)
        self.implementation_label_23.setGeometry(QtCore.QRect(40, 26, 101, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.implementation_label_23.sizePolicy().hasHeightForWidth())
        self.implementation_label_23.setSizePolicy(sizePolicy)
        self.implementation_label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.implementation_label_23.setObjectName(_fromUtf8("implementation_label_23"))
        self.POWER_R_L_eve_checkBox = QtGui.QCheckBox(self.road_power_page)
        self.POWER_R_L_eve_checkBox.setGeometry(QtCore.QRect(530, 20, 71, 22))
        self.POWER_R_L_eve_checkBox.setChecked(False)
        self.POWER_R_L_eve_checkBox.setObjectName(_fromUtf8("POWER_R_L_eve_checkBox"))
        self.POWER_R_L_day_checkBox = QtGui.QCheckBox(self.road_power_page)
        self.POWER_R_L_day_checkBox.setGeometry(QtCore.QRect(370, 20, 81, 22))
        self.POWER_R_L_day_checkBox.setChecked(False)
        self.POWER_R_L_day_checkBox.setObjectName(_fromUtf8("POWER_R_L_day_checkBox"))
        self.road_stackedWidget.addWidget(self.road_power_page)
        self.road_NMPB_page = QtGui.QWidget()
        self.road_NMPB_page.setObjectName(_fromUtf8("road_NMPB_page"))
        self.NMPB_L_gen_checkBox = QtGui.QCheckBox(self.road_NMPB_page)
        self.NMPB_L_gen_checkBox.setGeometry(QtCore.QRect(300, 20, 91, 21))
        self.NMPB_L_gen_checkBox.setChecked(True)
        self.NMPB_L_gen_checkBox.setObjectName(_fromUtf8("NMPB_L_gen_checkBox"))
        self.NMPB_L_nig_checkBox = QtGui.QCheckBox(self.road_NMPB_page)
        self.NMPB_L_nig_checkBox.setGeometry(QtCore.QRect(700, 20, 81, 22))
        self.NMPB_L_nig_checkBox.setChecked(False)
        self.NMPB_L_nig_checkBox.setObjectName(_fromUtf8("NMPB_L_nig_checkBox"))
        self.line_2 = QtGui.QFrame(self.road_NMPB_page)
        self.line_2.setWindowModality(QtCore.Qt.NonModal)
        self.line_2.setGeometry(QtCore.QRect(10, 40, 781, 20))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.NMPB_L_eve_checkBox = QtGui.QCheckBox(self.road_NMPB_page)
        self.NMPB_L_eve_checkBox.setGeometry(QtCore.QRect(570, 20, 71, 22))
        self.NMPB_L_eve_checkBox.setChecked(False)
        self.NMPB_L_eve_checkBox.setObjectName(_fromUtf8("NMPB_L_eve_checkBox"))
        self.NMPB_L_day_checkBox = QtGui.QCheckBox(self.road_NMPB_page)
        self.NMPB_L_day_checkBox.setGeometry(QtCore.QRect(430, 20, 81, 22))
        self.NMPB_L_day_checkBox.setChecked(False)
        self.NMPB_L_day_checkBox.setObjectName(_fromUtf8("NMPB_L_day_checkBox"))
        self.implementation_label_19 = QtGui.QLabel(self.road_NMPB_page)
        self.implementation_label_19.setGeometry(QtCore.QRect(150, 26, 101, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.implementation_label_19.sizePolicy().hasHeightForWidth())
        self.implementation_label_19.setSizePolicy(sizePolicy)
        self.implementation_label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.implementation_label_19.setObjectName(_fromUtf8("implementation_label_19"))
        self.line_8 = QtGui.QFrame(self.road_NMPB_page)
        self.line_8.setWindowModality(QtCore.Qt.NonModal)
        self.line_8.setGeometry(QtCore.QRect(10, 120, 781, 20))
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.verticalLayoutWidget_5 = QtGui.QWidget(self.road_NMPB_page)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(0, 60, 801, 61))
        self.verticalLayoutWidget_5.setObjectName(_fromUtf8("verticalLayoutWidget_5"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_2.setSpacing(1)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.NMPB_l_checkBox = QtGui.QCheckBox(self.verticalLayoutWidget_5)
        self.NMPB_l_checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.NMPB_l_checkBox.setAutoFillBackground(False)
        self.NMPB_l_checkBox.setObjectName(_fromUtf8("NMPB_l_checkBox"))
        self.horizontalLayout_3.addWidget(self.NMPB_l_checkBox)
        self.NMPB_l_n_label = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.NMPB_l_n_label.setMaximumSize(QtCore.QSize(16777215, 27))
        self.NMPB_l_n_label.setAlignment(QtCore.Qt.AlignCenter)
        self.NMPB_l_n_label.setObjectName(_fromUtf8("NMPB_l_n_label"))
        self.horizontalLayout_3.addWidget(self.NMPB_l_n_label)
        self.NMPB_L_gen_l_n_comboBox = QtGui.QComboBox(self.verticalLayoutWidget_5)
        self.NMPB_L_gen_l_n_comboBox.setMaximumSize(QtCore.QSize(16777215, 27))
        self.NMPB_L_gen_l_n_comboBox.setObjectName(_fromUtf8("NMPB_L_gen_l_n_comboBox"))
        self.horizontalLayout_3.addWidget(self.NMPB_L_gen_l_n_comboBox)
        self.NMPB_L_day_l_n_comboBox = QtGui.QComboBox(self.verticalLayoutWidget_5)
        self.NMPB_L_day_l_n_comboBox.setMaximumSize(QtCore.QSize(16777215, 27))
        self.NMPB_L_day_l_n_comboBox.setObjectName(_fromUtf8("NMPB_L_day_l_n_comboBox"))
        self.horizontalLayout_3.addWidget(self.NMPB_L_day_l_n_comboBox)
        self.NMPB_L_eve_l_n_comboBox = QtGui.QComboBox(self.verticalLayoutWidget_5)
        self.NMPB_L_eve_l_n_comboBox.setMaximumSize(QtCore.QSize(16777215, 27))
        self.NMPB_L_eve_l_n_comboBox.setObjectName(_fromUtf8("NMPB_L_eve_l_n_comboBox"))
        self.horizontalLayout_3.addWidget(self.NMPB_L_eve_l_n_comboBox)
        self.NMPB_L_nig_l_n_comboBox = QtGui.QComboBox(self.verticalLayoutWidget_5)
        self.NMPB_L_nig_l_n_comboBox.setMaximumSize(QtCore.QSize(16777215, 27))
        self.NMPB_L_nig_l_n_comboBox.setObjectName(_fromUtf8("NMPB_L_nig_l_n_comboBox"))
        self.horizontalLayout_3.addWidget(self.NMPB_L_nig_l_n_comboBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.implementation_label_6 = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.implementation_label_6.setMaximumSize(QtCore.QSize(16777215, 27))
        self.implementation_label_6.setText(_fromUtf8(""))
        self.implementation_label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.implementation_label_6.setObjectName(_fromUtf8("implementation_label_6"))
        self.horizontalLayout_5.addWidget(self.implementation_label_6)
        self.n_l_label_11 = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.n_l_label_11.setMaximumSize(QtCore.QSize(16777215, 27))
        self.n_l_label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.n_l_label_11.setObjectName(_fromUtf8("n_l_label_11"))
        self.horizontalLayout_5.addWidget(self.n_l_label_11)
        self.NMPB_L_gen_l_s_comboBox = QtGui.QComboBox(self.verticalLayoutWidget_5)
        self.NMPB_L_gen_l_s_comboBox.setMaximumSize(QtCore.QSize(16777215, 27))
        self.NMPB_L_gen_l_s_comboBox.setObjectName(_fromUtf8("NMPB_L_gen_l_s_comboBox"))
        self.horizontalLayout_5.addWidget(self.NMPB_L_gen_l_s_comboBox)
        self.NMPB_L_day_l_s_comboBox = QtGui.QComboBox(self.verticalLayoutWidget_5)
        self.NMPB_L_day_l_s_comboBox.setMaximumSize(QtCore.QSize(16777215, 27))
        self.NMPB_L_day_l_s_comboBox.setObjectName(_fromUtf8("NMPB_L_day_l_s_comboBox"))
        self.horizontalLayout_5.addWidget(self.NMPB_L_day_l_s_comboBox)
        self.NMPB_L_eve_l_s_comboBox = QtGui.QComboBox(self.verticalLayoutWidget_5)
        self.NMPB_L_eve_l_s_comboBox.setMaximumSize(QtCore.QSize(16777215, 27))
        self.NMPB_L_eve_l_s_comboBox.setObjectName(_fromUtf8("NMPB_L_eve_l_s_comboBox"))
        self.horizontalLayout_5.addWidget(self.NMPB_L_eve_l_s_comboBox)
        self.NMPB_L_nig_l_s_comboBox = QtGui.QComboBox(self.verticalLayoutWidget_5)
        self.NMPB_L_nig_l_s_comboBox.setMaximumSize(QtCore.QSize(16777215, 27))
        self.NMPB_L_nig_l_s_comboBox.setObjectName(_fromUtf8("NMPB_L_nig_l_s_comboBox"))
        self.horizontalLayout_5.addWidget(self.NMPB_L_nig_l_s_comboBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayoutWidget_6 = QtGui.QWidget(self.road_NMPB_page)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(0, 140, 801, 61))
        self.verticalLayoutWidget_6.setObjectName(_fromUtf8("verticalLayoutWidget_6"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_3.setSpacing(1)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.NMPB_h_checkBox = QtGui.QCheckBox(self.verticalLayoutWidget_6)
        self.NMPB_h_checkBox.setEnabled(True)
        self.NMPB_h_checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.NMPB_h_checkBox.setAutoFillBackground(False)
        self.NMPB_h_checkBox.setObjectName(_fromUtf8("NMPB_h_checkBox"))
        self.horizontalLayout_6.addWidget(self.NMPB_h_checkBox)
        self.n_l_label_12 = QtGui.QLabel(self.verticalLayoutWidget_6)
        self.n_l_label_12.setEnabled(True)
        self.n_l_label_12.setMaximumSize(QtCore.QSize(16777215, 27))
        self.n_l_label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.n_l_label_12.setObjectName(_fromUtf8("n_l_label_12"))
        self.horizontalLayout_6.addWidget(self.n_l_label_12)
        self.NMPB_L_gen_h_n_comboBox = QtGui.QComboBox(self.verticalLayoutWidget_6)
        self.NMPB_L_gen_h_n_comboBox.setMaximumSize(QtCore.QSize(16777215, 27))
        self.NMPB_L_gen_h_n_comboBox.setObjectName(_fromUtf8("NMPB_L_gen_h_n_comboBox"))
        self.horizontalLayout_6.addWidget(self.NMPB_L_gen_h_n_comboBox)
        self.NMPB_L_day_h_n_comboBox = QtGui.QComboBox(self.verticalLayoutWidget_6)
        self.NMPB_L_day_h_n_comboBox.setMaximumSize(QtCore.QSize(16777215, 27))
        self.NMPB_L_day_h_n_comboBox.setObjectName(_fromUtf8("NMPB_L_day_h_n_comboBox"))
        self.horizontalLayout_6.addWidget(self.NMPB_L_day_h_n_comboBox)
        self.NMPB_L_eve_h_n_comboBox = QtGui.QComboBox(self.verticalLayoutWidget_6)
        self.NMPB_L_eve_h_n_comboBox.setMaximumSize(QtCore.QSize(16777215, 27))
        self.NMPB_L_eve_h_n_comboBox.setObjectName(_fromUtf8("NMPB_L_eve_h_n_comboBox"))
        self.horizontalLayout_6.addWidget(self.NMPB_L_eve_h_n_comboBox)
        self.NMPB_L_nig_h_n_comboBox = QtGui.QComboBox(self.verticalLayoutWidget_6)
        self.NMPB_L_nig_h_n_comboBox.setMaximumSize(QtCore.QSize(16777215, 27))
        self.NMPB_L_nig_h_n_comboBox.setObjectName(_fromUtf8("NMPB_L_nig_h_n_comboBox"))
        self.horizontalLayout_6.addWidget(self.NMPB_L_nig_h_n_comboBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.implementation_label_8 = QtGui.QLabel(self.verticalLayoutWidget_6)
        self.implementation_label_8.setMaximumSize(QtCore.QSize(16777215, 27))
        self.implementation_label_8.setText(_fromUtf8(""))
        self.implementation_label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.implementation_label_8.setObjectName(_fromUtf8("implementation_label_8"))
        self.horizontalLayout_7.addWidget(self.implementation_label_8)
        self.n_l_label_13 = QtGui.QLabel(self.verticalLayoutWidget_6)
        self.n_l_label_13.setMaximumSize(QtCore.QSize(16777215, 27))
        self.n_l_label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.n_l_label_13.setObjectName(_fromUtf8("n_l_label_13"))
        self.horizontalLayout_7.addWidget(self.n_l_label_13)
        self.NMPB_L_gen_h_s_comboBox = QtGui.QComboBox(self.verticalLayoutWidget_6)
        self.NMPB_L_gen_h_s_comboBox.setMaximumSize(QtCore.QSize(16777215, 27))
        self.NMPB_L_gen_h_s_comboBox.setObjectName(_fromUtf8("NMPB_L_gen_h_s_comboBox"))
        self.horizontalLayout_7.addWidget(self.NMPB_L_gen_h_s_comboBox)
        self.NMPB_L_day_h_s_comboBox = QtGui.QComboBox(self.verticalLayoutWidget_6)
        self.NMPB_L_day_h_s_comboBox.setMaximumSize(QtCore.QSize(16777215, 27))
        self.NMPB_L_day_h_s_comboBox.setObjectName(_fromUtf8("NMPB_L_day_h_s_comboBox"))
        self.horizontalLayout_7.addWidget(self.NMPB_L_day_h_s_comboBox)
        self.NMPB_L_eve_h_s_comboBox = QtGui.QComboBox(self.verticalLayoutWidget_6)
        self.NMPB_L_eve_h_s_comboBox.setMaximumSize(QtCore.QSize(16777215, 27))
        self.NMPB_L_eve_h_s_comboBox.setObjectName(_fromUtf8("NMPB_L_eve_h_s_comboBox"))
        self.horizontalLayout_7.addWidget(self.NMPB_L_eve_h_s_comboBox)
        self.NMPB_L_nig_h_s_comboBox = QtGui.QComboBox(self.verticalLayoutWidget_6)
        self.NMPB_L_nig_h_s_comboBox.setMaximumSize(QtCore.QSize(16777215, 27))
        self.NMPB_L_nig_h_s_comboBox.setObjectName(_fromUtf8("NMPB_L_nig_h_s_comboBox"))
        self.horizontalLayout_7.addWidget(self.NMPB_L_nig_h_s_comboBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.implementation_label_21 = QtGui.QLabel(self.road_NMPB_page)
        self.implementation_label_21.setGeometry(QtCore.QRect(0, 26, 121, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.implementation_label_21.sizePolicy().hasHeightForWidth())
        self.implementation_label_21.setSizePolicy(sizePolicy)
        self.implementation_label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.implementation_label_21.setObjectName(_fromUtf8("implementation_label_21"))
        self.line_9 = QtGui.QFrame(self.road_NMPB_page)
        self.line_9.setWindowModality(QtCore.Qt.NonModal)
        self.line_9.setGeometry(QtCore.QRect(10, 200, 781, 20))
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.layoutWidget_3 = QtGui.QWidget(self.road_NMPB_page)
        self.layoutWidget_3.setGeometry(QtCore.QRect(0, 220, 801, 31))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_11.setMargin(0)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.implementation_label_25 = QtGui.QLabel(self.layoutWidget_3)
        self.implementation_label_25.setMaximumSize(QtCore.QSize(16777215, 27))
        self.implementation_label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.implementation_label_25.setObjectName(_fromUtf8("implementation_label_25"))
        self.horizontalLayout_11.addWidget(self.implementation_label_25)
        self.type_label = QtGui.QLabel(self.layoutWidget_3)
        self.type_label.setMaximumSize(QtCore.QSize(16777215, 27))
        self.type_label.setAlignment(QtCore.Qt.AlignCenter)
        self.type_label.setObjectName(_fromUtf8("type_label"))
        self.horizontalLayout_11.addWidget(self.type_label)
        self.NMPB_L_gen_type_comboBox = QtGui.QComboBox(self.layoutWidget_3)
        self.NMPB_L_gen_type_comboBox.setMaximumSize(QtCore.QSize(16777215, 27))
        self.NMPB_L_gen_type_comboBox.setObjectName(_fromUtf8("NMPB_L_gen_type_comboBox"))
        self.horizontalLayout_11.addWidget(self.NMPB_L_gen_type_comboBox)
        self.NMPB_L_day_type_comboBox = QtGui.QComboBox(self.layoutWidget_3)
        self.NMPB_L_day_type_comboBox.setMaximumSize(QtCore.QSize(16777215, 27))
        self.NMPB_L_day_type_comboBox.setObjectName(_fromUtf8("NMPB_L_day_type_comboBox"))
        self.horizontalLayout_11.addWidget(self.NMPB_L_day_type_comboBox)
        self.NMPB_L_eve_type_comboBox = QtGui.QComboBox(self.layoutWidget_3)
        self.NMPB_L_eve_type_comboBox.setMaximumSize(QtCore.QSize(16777215, 27))
        self.NMPB_L_eve_type_comboBox.setObjectName(_fromUtf8("NMPB_L_eve_type_comboBox"))
        self.horizontalLayout_11.addWidget(self.NMPB_L_eve_type_comboBox)
        self.NMPB_L_nig_type_comboBox = QtGui.QComboBox(self.layoutWidget_3)
        self.NMPB_L_nig_type_comboBox.setMaximumSize(QtCore.QSize(16777215, 27))
        self.NMPB_L_nig_type_comboBox.setObjectName(_fromUtf8("NMPB_L_nig_type_comboBox"))
        self.horizontalLayout_11.addWidget(self.NMPB_L_nig_type_comboBox)
        self.line_12 = QtGui.QFrame(self.road_NMPB_page)
        self.line_12.setWindowModality(QtCore.Qt.NonModal)
        self.line_12.setGeometry(QtCore.QRect(10, 252, 781, 20))
        self.line_12.setFrameShape(QtGui.QFrame.HLine)
        self.line_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_12.setObjectName(_fromUtf8("line_12"))
        self.slope_label_4 = QtGui.QLabel(self.road_NMPB_page)
        self.slope_label_4.setGeometry(QtCore.QRect(20, 312, 81, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slope_label_4.sizePolicy().hasHeightForWidth())
        self.slope_label_4.setSizePolicy(sizePolicy)
        self.slope_label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.slope_label_4.setObjectName(_fromUtf8("slope_label_4"))
        self.NMPB_surface_comboBox = QtGui.QComboBox(self.road_NMPB_page)
        self.NMPB_surface_comboBox.setGeometry(QtCore.QRect(90, 340, 131, 27))
        self.NMPB_surface_comboBox.setObjectName(_fromUtf8("NMPB_surface_comboBox"))
        self.surface_label_4 = QtGui.QLabel(self.road_NMPB_page)
        self.surface_label_4.setGeometry(QtCore.QRect(20, 342, 71, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.surface_label_4.sizePolicy().hasHeightForWidth())
        self.surface_label_4.setSizePolicy(sizePolicy)
        self.surface_label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.surface_label_4.setObjectName(_fromUtf8("surface_label_4"))
        self.implementation_label_27 = QtGui.QLabel(self.road_NMPB_page)
        self.implementation_label_27.setGeometry(QtCore.QRect(20, 275, 431, 27))
        self.implementation_label_27.setMaximumSize(QtCore.QSize(16777215, 27))
        self.implementation_label_27.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.implementation_label_27.setObjectName(_fromUtf8("implementation_label_27"))
        self.NMPB_slope_comboBox = QtGui.QComboBox(self.road_NMPB_page)
        self.NMPB_slope_comboBox.setGeometry(QtCore.QRect(90, 309, 131, 27))
        self.NMPB_slope_comboBox.setToolTip(_fromUtf8(""))
        self.NMPB_slope_comboBox.setStatusTip(_fromUtf8(""))
        self.NMPB_slope_comboBox.setWhatsThis(_fromUtf8(""))
        self.NMPB_slope_comboBox.setAccessibleName(_fromUtf8(""))
        self.NMPB_slope_comboBox.setAccessibleDescription(_fromUtf8(""))
        self.NMPB_slope_comboBox.setObjectName(_fromUtf8("NMPB_slope_comboBox"))
        self.road_stackedWidget.addWidget(self.road_NMPB_page)
        self.road_CNOSSOS_page = QtGui.QWidget()
        self.road_CNOSSOS_page.setObjectName(_fromUtf8("road_CNOSSOS_page"))
        self.CNOSSOS_L_nig_checkBox = QtGui.QCheckBox(self.road_CNOSSOS_page)
        self.CNOSSOS_L_nig_checkBox.setGeometry(QtCore.QRect(700, 20, 81, 22))
        self.CNOSSOS_L_nig_checkBox.setChecked(False)
        self.CNOSSOS_L_nig_checkBox.setObjectName(_fromUtf8("CNOSSOS_L_nig_checkBox"))
        self.CNOSSOS_L_gen_checkBox = QtGui.QCheckBox(self.road_CNOSSOS_page)
        self.CNOSSOS_L_gen_checkBox.setGeometry(QtCore.QRect(300, 20, 91, 21))
        self.CNOSSOS_L_gen_checkBox.setChecked(True)
        self.CNOSSOS_L_gen_checkBox.setObjectName(_fromUtf8("CNOSSOS_L_gen_checkBox"))
        self.CNOSSOS_L_eve_checkBox = QtGui.QCheckBox(self.road_CNOSSOS_page)
        self.CNOSSOS_L_eve_checkBox.setGeometry(QtCore.QRect(570, 20, 71, 22))
        self.CNOSSOS_L_eve_checkBox.setChecked(False)
        self.CNOSSOS_L_eve_checkBox.setObjectName(_fromUtf8("CNOSSOS_L_eve_checkBox"))
        self.CNOSSOS_L_day_checkBox = QtGui.QCheckBox(self.road_CNOSSOS_page)
        self.CNOSSOS_L_day_checkBox.setGeometry(QtCore.QRect(430, 20, 81, 22))
        self.CNOSSOS_L_day_checkBox.setChecked(False)
        self.CNOSSOS_L_day_checkBox.setObjectName(_fromUtf8("CNOSSOS_L_day_checkBox"))
        self.line = QtGui.QFrame(self.road_CNOSSOS_page)
        self.line.setWindowModality(QtCore.Qt.NonModal)
        self.line.setGeometry(QtCore.QRect(10, 40, 781, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.implementation_label_9 = QtGui.QLabel(self.road_CNOSSOS_page)
        self.implementation_label_9.setGeometry(QtCore.QRect(150, 26, 101, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.implementation_label_9.sizePolicy().hasHeightForWidth())
        self.implementation_label_9.setSizePolicy(sizePolicy)
        self.implementation_label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.implementation_label_9.setObjectName(_fromUtf8("implementation_label_9"))
        self.verticalLayoutWidget_8 = QtGui.QWidget(self.road_CNOSSOS_page)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(0, 125, 801, 61))
        self.verticalLayoutWidget_8.setObjectName(_fromUtf8("verticalLayoutWidget_8"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_6.setSpacing(1)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.CNOSSOS_2_checkBox = QtGui.QCheckBox(self.verticalLayoutWidget_8)
        self.CNOSSOS_2_checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.CNOSSOS_2_checkBox.setAutoFillBackground(False)
        self.CNOSSOS_2_checkBox.setObjectName(_fromUtf8("CNOSSOS_2_checkBox"))
        self.horizontalLayout_12.addWidget(self.CNOSSOS_2_checkBox)
        self.n_l_label_18 = QtGui.QLabel(self.verticalLayoutWidget_8)
        self.n_l_label_18.setMaximumSize(QtCore.QSize(16777215, 27))
        self.n_l_label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.n_l_label_18.setObjectName(_fromUtf8("n_l_label_18"))
        self.horizontalLayout_12.addWidget(self.n_l_label_18)
        self.CNOSSOS_L_gen_2_n_comboBox = QtGui.QComboBox(self.verticalLayoutWidget_8)
        self.CNOSSOS_L_gen_2_n_comboBox.setMaximumSize(QtCore.QSize(16777215, 27))
        self.CNOSSOS_L_gen_2_n_comboBox.setObjectName(_fromUtf8("CNOSSOS_L_gen_2_n_comboBox"))
        self.horizontalLayout_12.addWidget(self.CNOSSOS_L_gen_2_n_comboBox)
        self.CNOSSOS_L_day_2_n_comboBox = QtGui.QComboBox(self.verticalLayoutWidget_8)
        self.CNOSSOS_L_day_2_n_comboBox.setMaximumSize(QtCore.QSize(16777215, 27))
        self.CNOSSOS_L_day_2_n_comboBox.setObjectName(_fromUtf8("CNOSSOS_L_day_2_n_comboBox"))
        self.horizontalLayout_12.addWidget(self.CNOSSOS_L_day_2_n_comboBox)
        self.CNOSSOS_L_eve_2_n_comboBox = QtGui.QComboBox(self.verticalLayoutWidget_8)
        self.CNOSSOS_L_eve_2_n_comboBox.setMaximumSize(QtCore.QSize(16777215, 27))
        self.CNOSSOS_L_eve_2_n_comboBox.setObjectName(_fromUtf8("CNOSSOS_L_eve_2_n_comboBox"))
        self.horizontalLayout_12.addWidget(self.CNOSSOS_L_eve_2_n_comboBox)
        self.CNOSSOS_L_nig_2_n_comboBox = QtGui.QComboBox(self.verticalLayoutWidget_8)
        self.CNOSSOS_L_nig_2_n_comboBox.setMaximumSize(QtCore.QSize(16777215, 27))
        self.CNOSSOS_L_nig_2_n_comboBox.setObjectName(_fromUtf8("CNOSSOS_L_nig_2_n_comboBox"))
        self.horizontalLayout_12.addWidget(self.CNOSSOS_L_nig_2_n_comboBox)
        self.verticalLayout_6.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.implementation_label_10 = QtGui.QLabel(self.verticalLayoutWidget_8)
        self.implementation_label_10.setMaximumSize(QtCore.QSize(16777215, 27))
        self.implementation_label_10.setText(_fromUtf8(""))
        self.implementation_label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.implementation_label_10.setObjectName(_fromUtf8("implementation_label_10"))
        self.horizontalLayout_13.addWidget(self.implementation_label_10)
        self.n_l_label_19 = QtGui.QLabel(self.verticalLayoutWidget_8)
        self.n_l_label_19.setMaximumSize(QtCore.QSize(16777215, 27))
        self.n_l_label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.n_l_label_19.setObjectName(_fromUtf8("n_l_label_19"))
        self.horizontalLayout_13.addWidget(self.n_l_label_19)
        self.CNOSSOS_L_gen_2_s_comboBox = QtGui.QComboBox(self.verticalLayoutWidget_8)
        self.CNOSSOS_L_gen_2_s_comboBox.setMaximumSize(QtCore.QSize(16777215, 27))
        self.CNOSSOS_L_gen_2_s_comboBox.setObjectName(_fromUtf8("CNOSSOS_L_gen_2_s_comboBox"))
        self.horizontalLayout_13.addWidget(self.CNOSSOS_L_gen_2_s_comboBox)
        self.CNOSSOS_L_day_2_s_comboBox = QtGui.QComboBox(self.verticalLayoutWidget_8)
        self.CNOSSOS_L_day_2_s_comboBox.setMaximumSize(QtCore.QSize(16777215, 27))
        self.CNOSSOS_L_day_2_s_comboBox.setObjectName(_fromUtf8("CNOSSOS_L_day_2_s_comboBox"))
        self.horizontalLayout_13.addWidget(self.CNOSSOS_L_day_2_s_comboBox)
        self.CNOSSOS_L_eve_2_s_comboBox = QtGui.QComboBox(self.verticalLayoutWidget_8)
        self.CNOSSOS_L_eve_2_s_comboBox.setMaximumSize(QtCore.QSize(16777215, 27))
        self.CNOSSOS_L_eve_2_s_comboBox.setObjectName(_fromUtf8("CNOSSOS_L_eve_2_s_comboBox"))
        self.horizontalLayout_13.addWidget(self.CNOSSOS_L_eve_2_s_comboBox)
        self.CNOSSOS_L_nig_2_s_comboBox = QtGui.QComboBox(self.verticalLayoutWidget_8)
        self.CNOSSOS_L_nig_2_s_comboBox.setMaximumSize(QtCore.QSize(16777215, 27))
        self.CNOSSOS_L_nig_2_s_comboBox.setObjectName(_fromUtf8("CNOSSOS_L_nig_2_s_comboBox"))
        self.horizontalLayout_13.addWidget(self.CNOSSOS_L_nig_2_s_comboBox)
        self.verticalLayout_6.addLayout(self.horizontalLayout_13)
        self.line_3 = QtGui.QFrame(self.road_CNOSSOS_page)
        self.line_3.setWindowModality(QtCore.Qt.NonModal)
        self.line_3.setGeometry(QtCore.QRect(10, 110, 781, 20))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayoutWidget_9 = QtGui.QWidget(self.road_CNOSSOS_page)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(0, 196, 801, 61))
        self.verticalLayoutWidget_9.setObjectName(_fromUtf8("verticalLayoutWidget_9"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.verticalLayoutWidget_9)
        self.verticalLayout_7.setSpacing(1)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.CNOSSOS_3_checkBox = QtGui.QCheckBox(self.verticalLayoutWidget_9)
        self.CNOSSOS_3_checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.CNOSSOS_3_checkBox.setAutoFillBackground(False)
        self.CNOSSOS_3_checkBox.setObjectName(_fromUtf8("CNOSSOS_3_checkBox"))
        self.horizontalLayout_14.addWidget(self.CNOSSOS_3_checkBox)
        self.n_l_label_20 = QtGui.QLabel(self.verticalLayoutWidget_9)
        self.n_l_label_20.setMaximumSize(QtCore.QSize(16777215, 27))
        self.n_l_label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.n_l_label_20.setObjectName(_fromUtf8("n_l_label_20"))
        self.horizontalLayout_14.addWidget(self.n_l_label_20)
        self.CNOSSOS_L_gen_3_n_comboBox = QtGui.QComboBox(self.verticalLayoutWidget_9)
        self.CNOSSOS_L_gen_3_n_comboBox.setMaximumSize(QtCore.QSize(16777215, 27))
        self.CNOSSOS_L_gen_3_n_comboBox.setObjectName(_fromUtf8("CNOSSOS_L_gen_3_n_comboBox"))
        self.horizontalLayout_14.addWidget(self.CNOSSOS_L_gen_3_n_comboBox)
        self.CNOSSOS_L_day_3_n_comboBox = QtGui.QComboBox(self.verticalLayoutWidget_9)
        self.CNOSSOS_L_day_3_n_comboBox.setMaximumSize(QtCore.QSize(16777215, 27))
        self.CNOSSOS_L_day_3_n_comboBox.setObjectName(_fromUtf8("CNOSSOS_L_day_3_n_comboBox"))
        self.horizontalLayout_14.addWidget(self.CNOSSOS_L_day_3_n_comboBox)
        self.CNOSSOS_L_eve_3_n_comboBox = QtGui.QComboBox(self.verticalLayoutWidget_9)
        self.CNOSSOS_L_eve_3_n_comboBox.setMaximumSize(QtCore.QSize(16777215, 27))
        self.CNOSSOS_L_eve_3_n_comboBox.setObjectName(_fromUtf8("CNOSSOS_L_eve_3_n_comboBox"))
        self.horizontalLayout_14.addWidget(self.CNOSSOS_L_eve_3_n_comboBox)
        self.CNOSSOS_L_nig_3_n_comboBox = QtGui.QComboBox(self.verticalLayoutWidget_9)
        self.CNOSSOS_L_nig_3_n_comboBox.setMaximumSize(QtCore.QSize(16777215, 27))
        self.CNOSSOS_L_nig_3_n_comboBox.setObjectName(_fromUtf8("CNOSSOS_L_nig_3_n_comboBox"))
        self.horizontalLayout_14.addWidget(self.CNOSSOS_L_nig_3_n_comboBox)
        self.verticalLayout_7.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.implementation_label_12 = QtGui.QLabel(self.verticalLayoutWidget_9)
        self.implementation_label_12.setMaximumSize(QtCore.QSize(16777215, 27))
        self.implementation_label_12.setText(_fromUtf8(""))
        self.implementation_label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.implementation_label_12.setObjectName(_fromUtf8("implementation_label_12"))
        self.horizontalLayout_15.addWidget(self.implementation_label_12)
        self.n_l_label_21 = QtGui.QLabel(self.verticalLayoutWidget_9)
        self.n_l_label_21.setMaximumSize(QtCore.QSize(16777215, 27))
        self.n_l_label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.n_l_label_21.setObjectName(_fromUtf8("n_l_label_21"))
        self.horizontalLayout_15.addWidget(self.n_l_label_21)
        self.CNOSSOS_L_gen_3_s_comboBox = QtGui.QComboBox(self.verticalLayoutWidget_9)
        self.CNOSSOS_L_gen_3_s_comboBox.setMaximumSize(QtCore.QSize(16777215, 27))
        self.CNOSSOS_L_gen_3_s_comboBox.setObjectName(_fromUtf8("CNOSSOS_L_gen_3_s_comboBox"))
        self.horizontalLayout_15.addWidget(self.CNOSSOS_L_gen_3_s_comboBox)
        self.CNOSSOS_L_day_3_s_comboBox = QtGui.QComboBox(self.verticalLayoutWidget_9)
        self.CNOSSOS_L_day_3_s_comboBox.setMaximumSize(QtCore.QSize(16777215, 27))
        self.CNOSSOS_L_day_3_s_comboBox.setObjectName(_fromUtf8("CNOSSOS_L_day_3_s_comboBox"))
        self.horizontalLayout_15.addWidget(self.CNOSSOS_L_day_3_s_comboBox)
        self.CNOSSOS_L_eve_3_s_comboBox = QtGui.QComboBox(self.verticalLayoutWidget_9)
        self.CNOSSOS_L_eve_3_s_comboBox.setMaximumSize(QtCore.QSize(16777215, 27))
        self.CNOSSOS_L_eve_3_s_comboBox.setObjectName(_fromUtf8("CNOSSOS_L_eve_3_s_comboBox"))
        self.horizontalLayout_15.addWidget(self.CNOSSOS_L_eve_3_s_comboBox)
        self.CNOSSOS_L_nig_3_s_comboBox = QtGui.QComboBox(self.verticalLayoutWidget_9)
        self.CNOSSOS_L_nig_3_s_comboBox.setMaximumSize(QtCore.QSize(16777215, 27))
        self.CNOSSOS_L_nig_3_s_comboBox.setObjectName(_fromUtf8("CNOSSOS_L_nig_3_s_comboBox"))
        self.horizontalLayout_15.addWidget(self.CNOSSOS_L_nig_3_s_comboBox)
        self.verticalLayout_7.addLayout(self.horizontalLayout_15)
        self.line_4 = QtGui.QFrame(self.road_CNOSSOS_page)
        self.line_4.setWindowModality(QtCore.Qt.NonModal)
        self.line_4.setGeometry(QtCore.QRect(10, 180, 781, 20))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayoutWidget_10 = QtGui.QWidget(self.road_CNOSSOS_page)
        self.verticalLayoutWidget_10.setGeometry(QtCore.QRect(0, 266, 801, 61))
        self.verticalLayoutWidget_10.setObjectName(_fromUtf8("verticalLayoutWidget_10"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.verticalLayoutWidget_10)
        self.verticalLayout_8.setSpacing(1)
        self.verticalLayout_8.setMargin(0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.CNOSSOS_4a_checkBox = QtGui.QCheckBox(self.verticalLayoutWidget_10)
        self.CNOSSOS_4a_checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.CNOSSOS_4a_checkBox.setAutoFillBackground(False)
        self.CNOSSOS_4a_checkBox.setObjectName(_fromUtf8("CNOSSOS_4a_checkBox"))
        self.horizontalLayout_16.addWidget(self.CNOSSOS_4a_checkBox)
        self.n_l_label_22 = QtGui.QLabel(self.verticalLayoutWidget_10)
        self.n_l_label_22.setMaximumSize(QtCore.QSize(16777215, 27))
        self.n_l_label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.n_l_label_22.setObjectName(_fromUtf8("n_l_label_22"))
        self.horizontalLayout_16.addWidget(self.n_l_label_22)
        self.CNOSSOS_L_gen_4a_n_comboBox = QtGui.QComboBox(self.verticalLayoutWidget_10)
        self.CNOSSOS_L_gen_4a_n_comboBox.setMaximumSize(QtCore.QSize(16777215, 27))
        self.CNOSSOS_L_gen_4a_n_comboBox.setObjectName(_fromUtf8("CNOSSOS_L_gen_4a_n_comboBox"))
        self.horizontalLayout_16.addWidget(self.CNOSSOS_L_gen_4a_n_comboBox)
        self.CNOSSOS_L_day_4a_n_comboBox = QtGui.QComboBox(self.verticalLayoutWidget_10)
        self.CNOSSOS_L_day_4a_n_comboBox.setMaximumSize(QtCore.QSize(16777215, 27))
        self.CNOSSOS_L_day_4a_n_comboBox.setObjectName(_fromUtf8("CNOSSOS_L_day_4a_n_comboBox"))
        self.horizontalLayout_16.addWidget(self.CNOSSOS_L_day_4a_n_comboBox)
        self.CNOSSOS_L_eve_4a_n_comboBox = QtGui.QComboBox(self.verticalLayoutWidget_10)
        self.CNOSSOS_L_eve_4a_n_comboBox.setMaximumSize(QtCore.QSize(16777215, 27))
        self.CNOSSOS_L_eve_4a_n_comboBox.setObjectName(_fromUtf8("CNOSSOS_L_eve_4a_n_comboBox"))
        self.horizontalLayout_16.addWidget(self.CNOSSOS_L_eve_4a_n_comboBox)
        self.CNOSSOS_L_nig_4a_n_comboBox = QtGui.QComboBox(self.verticalLayoutWidget_10)
        self.CNOSSOS_L_nig_4a_n_comboBox.setMaximumSize(QtCore.QSize(16777215, 27))
        self.CNOSSOS_L_nig_4a_n_comboBox.setObjectName(_fromUtf8("CNOSSOS_L_nig_4a_n_comboBox"))
        self.horizontalLayout_16.addWidget(self.CNOSSOS_L_nig_4a_n_comboBox)
        self.verticalLayout_8.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.implementation_label_14 = QtGui.QLabel(self.verticalLayoutWidget_10)
        self.implementation_label_14.setMaximumSize(QtCore.QSize(16777215, 27))
        self.implementation_label_14.setText(_fromUtf8(""))
        self.implementation_label_14.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.implementation_label_14.setObjectName(_fromUtf8("implementation_label_14"))
        self.horizontalLayout_17.addWidget(self.implementation_label_14)
        self.n_l_label_23 = QtGui.QLabel(self.verticalLayoutWidget_10)
        self.n_l_label_23.setMaximumSize(QtCore.QSize(16777215, 27))
        self.n_l_label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.n_l_label_23.setObjectName(_fromUtf8("n_l_label_23"))
        self.horizontalLayout_17.addWidget(self.n_l_label_23)
        self.CNOSSOS_L_gen_4a_s_comboBox = QtGui.QComboBox(self.verticalLayoutWidget_10)
        self.CNOSSOS_L_gen_4a_s_comboBox.setMaximumSize(QtCore.QSize(16777215, 27))
        self.CNOSSOS_L_gen_4a_s_comboBox.setObjectName(_fromUtf8("CNOSSOS_L_gen_4a_s_comboBox"))
        self.horizontalLayout_17.addWidget(self.CNOSSOS_L_gen_4a_s_comboBox)
        self.CNOSSOS_L_day_4a_s_comboBox = QtGui.QComboBox(self.verticalLayoutWidget_10)
        self.CNOSSOS_L_day_4a_s_comboBox.setMaximumSize(QtCore.QSize(16777215, 27))
        self.CNOSSOS_L_day_4a_s_comboBox.setObjectName(_fromUtf8("CNOSSOS_L_day_4a_s_comboBox"))
        self.horizontalLayout_17.addWidget(self.CNOSSOS_L_day_4a_s_comboBox)
        self.CNOSSOS_L_eve_4a_s_comboBox = QtGui.QComboBox(self.verticalLayoutWidget_10)
        self.CNOSSOS_L_eve_4a_s_comboBox.setMaximumSize(QtCore.QSize(16777215, 27))
        self.CNOSSOS_L_eve_4a_s_comboBox.setObjectName(_fromUtf8("CNOSSOS_L_eve_4a_s_comboBox"))
        self.horizontalLayout_17.addWidget(self.CNOSSOS_L_eve_4a_s_comboBox)
        self.CNOSSOS_L_nig_4a_s_comboBox = QtGui.QComboBox(self.verticalLayoutWidget_10)
        self.CNOSSOS_L_nig_4a_s_comboBox.setMaximumSize(QtCore.QSize(16777215, 27))
        self.CNOSSOS_L_nig_4a_s_comboBox.setObjectName(_fromUtf8("CNOSSOS_L_nig_4a_s_comboBox"))
        self.horizontalLayout_17.addWidget(self.CNOSSOS_L_nig_4a_s_comboBox)
        self.verticalLayout_8.addLayout(self.horizontalLayout_17)
        self.line_5 = QtGui.QFrame(self.road_CNOSSOS_page)
        self.line_5.setWindowModality(QtCore.Qt.NonModal)
        self.line_5.setGeometry(QtCore.QRect(10, 250, 781, 20))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.verticalLayoutWidget_11 = QtGui.QWidget(self.road_CNOSSOS_page)
        self.verticalLayoutWidget_11.setGeometry(QtCore.QRect(0, 336, 801, 61))
        self.verticalLayoutWidget_11.setObjectName(_fromUtf8("verticalLayoutWidget_11"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.verticalLayoutWidget_11)
        self.verticalLayout_9.setSpacing(1)
        self.verticalLayout_9.setMargin(0)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.CNOSSOS_4b_checkBox = QtGui.QCheckBox(self.verticalLayoutWidget_11)
        self.CNOSSOS_4b_checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.CNOSSOS_4b_checkBox.setAutoFillBackground(False)
        self.CNOSSOS_4b_checkBox.setObjectName(_fromUtf8("CNOSSOS_4b_checkBox"))
        self.horizontalLayout_18.addWidget(self.CNOSSOS_4b_checkBox)
        self.n_l_label_24 = QtGui.QLabel(self.verticalLayoutWidget_11)
        self.n_l_label_24.setMaximumSize(QtCore.QSize(16777215, 27))
        self.n_l_label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.n_l_label_24.setObjectName(_fromUtf8("n_l_label_24"))
        self.horizontalLayout_18.addWidget(self.n_l_label_24)
        self.CNOSSOS_L_gen_4b_n_comboBox = QtGui.QComboBox(self.verticalLayoutWidget_11)
        self.CNOSSOS_L_gen_4b_n_comboBox.setMaximumSize(QtCore.QSize(16777215, 27))
        self.CNOSSOS_L_gen_4b_n_comboBox.setObjectName(_fromUtf8("CNOSSOS_L_gen_4b_n_comboBox"))
        self.horizontalLayout_18.addWidget(self.CNOSSOS_L_gen_4b_n_comboBox)
        self.CNOSSOS_L_day_4b_n_comboBox = QtGui.QComboBox(self.verticalLayoutWidget_11)
        self.CNOSSOS_L_day_4b_n_comboBox.setMaximumSize(QtCore.QSize(16777215, 27))
        self.CNOSSOS_L_day_4b_n_comboBox.setObjectName(_fromUtf8("CNOSSOS_L_day_4b_n_comboBox"))
        self.horizontalLayout_18.addWidget(self.CNOSSOS_L_day_4b_n_comboBox)
        self.CNOSSOS_L_eve_4b_n_comboBox = QtGui.QComboBox(self.verticalLayoutWidget_11)
        self.CNOSSOS_L_eve_4b_n_comboBox.setMaximumSize(QtCore.QSize(16777215, 27))
        self.CNOSSOS_L_eve_4b_n_comboBox.setObjectName(_fromUtf8("CNOSSOS_L_eve_4b_n_comboBox"))
        self.horizontalLayout_18.addWidget(self.CNOSSOS_L_eve_4b_n_comboBox)
        self.CNOSSOS_L_nig_4b_n_comboBox = QtGui.QComboBox(self.verticalLayoutWidget_11)
        self.CNOSSOS_L_nig_4b_n_comboBox.setMaximumSize(QtCore.QSize(16777215, 27))
        self.CNOSSOS_L_nig_4b_n_comboBox.setObjectName(_fromUtf8("CNOSSOS_L_nig_4b_n_comboBox"))
        self.horizontalLayout_18.addWidget(self.CNOSSOS_L_nig_4b_n_comboBox)
        self.verticalLayout_9.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.implementation_label_16 = QtGui.QLabel(self.verticalLayoutWidget_11)
        self.implementation_label_16.setMaximumSize(QtCore.QSize(16777215, 27))
        self.implementation_label_16.setText(_fromUtf8(""))
        self.implementation_label_16.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.implementation_label_16.setObjectName(_fromUtf8("implementation_label_16"))
        self.horizontalLayout_19.addWidget(self.implementation_label_16)
        self.n_l_label_25 = QtGui.QLabel(self.verticalLayoutWidget_11)
        self.n_l_label_25.setMaximumSize(QtCore.QSize(16777215, 27))
        self.n_l_label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.n_l_label_25.setObjectName(_fromUtf8("n_l_label_25"))
        self.horizontalLayout_19.addWidget(self.n_l_label_25)
        self.CNOSSOS_L_gen_4b_s_comboBox = QtGui.QComboBox(self.verticalLayoutWidget_11)
        self.CNOSSOS_L_gen_4b_s_comboBox.setMaximumSize(QtCore.QSize(16777215, 27))
        self.CNOSSOS_L_gen_4b_s_comboBox.setObjectName(_fromUtf8("CNOSSOS_L_gen_4b_s_comboBox"))
        self.horizontalLayout_19.addWidget(self.CNOSSOS_L_gen_4b_s_comboBox)
        self.CNOSSOS_L_day_4b_s_comboBox = QtGui.QComboBox(self.verticalLayoutWidget_11)
        self.CNOSSOS_L_day_4b_s_comboBox.setMaximumSize(QtCore.QSize(16777215, 27))
        self.CNOSSOS_L_day_4b_s_comboBox.setObjectName(_fromUtf8("CNOSSOS_L_day_4b_s_comboBox"))
        self.horizontalLayout_19.addWidget(self.CNOSSOS_L_day_4b_s_comboBox)
        self.CNOSSOS_L_eve_4b_s_comboBox = QtGui.QComboBox(self.verticalLayoutWidget_11)
        self.CNOSSOS_L_eve_4b_s_comboBox.setMaximumSize(QtCore.QSize(16777215, 27))
        self.CNOSSOS_L_eve_4b_s_comboBox.setObjectName(_fromUtf8("CNOSSOS_L_eve_4b_s_comboBox"))
        self.horizontalLayout_19.addWidget(self.CNOSSOS_L_eve_4b_s_comboBox)
        self.CNOSSOS_L_nig_4b_s_comboBox = QtGui.QComboBox(self.verticalLayoutWidget_11)
        self.CNOSSOS_L_nig_4b_s_comboBox.setMaximumSize(QtCore.QSize(16777215, 27))
        self.CNOSSOS_L_nig_4b_s_comboBox.setObjectName(_fromUtf8("CNOSSOS_L_nig_4b_s_comboBox"))
        self.horizontalLayout_19.addWidget(self.CNOSSOS_L_nig_4b_s_comboBox)
        self.verticalLayout_9.addLayout(self.horizontalLayout_19)
        self.line_6 = QtGui.QFrame(self.road_CNOSSOS_page)
        self.line_6.setWindowModality(QtCore.Qt.NonModal)
        self.line_6.setGeometry(QtCore.QRect(10, 320, 781, 20))
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.line_7 = QtGui.QFrame(self.road_CNOSSOS_page)
        self.line_7.setWindowModality(QtCore.Qt.NonModal)
        self.line_7.setGeometry(QtCore.QRect(10, 390, 781, 20))
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.implementation_label_20 = QtGui.QLabel(self.road_CNOSSOS_page)
        self.implementation_label_20.setGeometry(QtCore.QRect(0, 26, 121, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.implementation_label_20.sizePolicy().hasHeightForWidth())
        self.implementation_label_20.setSizePolicy(sizePolicy)
        self.implementation_label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.implementation_label_20.setObjectName(_fromUtf8("implementation_label_20"))
        self.verticalLayoutWidget_13 = QtGui.QWidget(self.road_CNOSSOS_page)
        self.verticalLayoutWidget_13.setGeometry(QtCore.QRect(0, 55, 801, 61))
        self.verticalLayoutWidget_13.setObjectName(_fromUtf8("verticalLayoutWidget_13"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.verticalLayoutWidget_13)
        self.verticalLayout_11.setSpacing(1)
        self.verticalLayout_11.setMargin(0)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.CNOSSOS_1_checkBox = QtGui.QCheckBox(self.verticalLayoutWidget_13)
        self.CNOSSOS_1_checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.CNOSSOS_1_checkBox.setAutoFillBackground(False)
        self.CNOSSOS_1_checkBox.setObjectName(_fromUtf8("CNOSSOS_1_checkBox"))
        self.horizontalLayout_22.addWidget(self.CNOSSOS_1_checkBox)
        self.n_l_label_28 = QtGui.QLabel(self.verticalLayoutWidget_13)
        self.n_l_label_28.setMaximumSize(QtCore.QSize(16777215, 27))
        self.n_l_label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.n_l_label_28.setObjectName(_fromUtf8("n_l_label_28"))
        self.horizontalLayout_22.addWidget(self.n_l_label_28)
        self.CNOSSOS_L_gen_1_n_comboBox = QtGui.QComboBox(self.verticalLayoutWidget_13)
        self.CNOSSOS_L_gen_1_n_comboBox.setMaximumSize(QtCore.QSize(16777215, 27))
        self.CNOSSOS_L_gen_1_n_comboBox.setObjectName(_fromUtf8("CNOSSOS_L_gen_1_n_comboBox"))
        self.horizontalLayout_22.addWidget(self.CNOSSOS_L_gen_1_n_comboBox)
        self.CNOSSOS_L_day_1_n_comboBox = QtGui.QComboBox(self.verticalLayoutWidget_13)
        self.CNOSSOS_L_day_1_n_comboBox.setMaximumSize(QtCore.QSize(16777215, 27))
        self.CNOSSOS_L_day_1_n_comboBox.setObjectName(_fromUtf8("CNOSSOS_L_day_1_n_comboBox"))
        self.horizontalLayout_22.addWidget(self.CNOSSOS_L_day_1_n_comboBox)
        self.CNOSSOS_L_eve_1_n_comboBox = QtGui.QComboBox(self.verticalLayoutWidget_13)
        self.CNOSSOS_L_eve_1_n_comboBox.setMaximumSize(QtCore.QSize(16777215, 27))
        self.CNOSSOS_L_eve_1_n_comboBox.setObjectName(_fromUtf8("CNOSSOS_L_eve_1_n_comboBox"))
        self.horizontalLayout_22.addWidget(self.CNOSSOS_L_eve_1_n_comboBox)
        self.CNOSSOS_L_nig_1_n_comboBox = QtGui.QComboBox(self.verticalLayoutWidget_13)
        self.CNOSSOS_L_nig_1_n_comboBox.setMaximumSize(QtCore.QSize(16777215, 27))
        self.CNOSSOS_L_nig_1_n_comboBox.setObjectName(_fromUtf8("CNOSSOS_L_nig_1_n_comboBox"))
        self.horizontalLayout_22.addWidget(self.CNOSSOS_L_nig_1_n_comboBox)
        self.verticalLayout_11.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.implementation_label_22 = QtGui.QLabel(self.verticalLayoutWidget_13)
        self.implementation_label_22.setMaximumSize(QtCore.QSize(16777215, 27))
        self.implementation_label_22.setText(_fromUtf8(""))
        self.implementation_label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.implementation_label_22.setObjectName(_fromUtf8("implementation_label_22"))
        self.horizontalLayout_23.addWidget(self.implementation_label_22)
        self.n_l_label_29 = QtGui.QLabel(self.verticalLayoutWidget_13)
        self.n_l_label_29.setMaximumSize(QtCore.QSize(16777215, 27))
        self.n_l_label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.n_l_label_29.setObjectName(_fromUtf8("n_l_label_29"))
        self.horizontalLayout_23.addWidget(self.n_l_label_29)
        self.CNOSSOS_L_gen_1_s_comboBox = QtGui.QComboBox(self.verticalLayoutWidget_13)
        self.CNOSSOS_L_gen_1_s_comboBox.setMaximumSize(QtCore.QSize(16777215, 27))
        self.CNOSSOS_L_gen_1_s_comboBox.setObjectName(_fromUtf8("CNOSSOS_L_gen_1_s_comboBox"))
        self.horizontalLayout_23.addWidget(self.CNOSSOS_L_gen_1_s_comboBox)
        self.CNOSSOS_L_day_1_s_comboBox = QtGui.QComboBox(self.verticalLayoutWidget_13)
        self.CNOSSOS_L_day_1_s_comboBox.setMaximumSize(QtCore.QSize(16777215, 27))
        self.CNOSSOS_L_day_1_s_comboBox.setObjectName(_fromUtf8("CNOSSOS_L_day_1_s_comboBox"))
        self.horizontalLayout_23.addWidget(self.CNOSSOS_L_day_1_s_comboBox)
        self.CNOSSOS_L_eve_1_s_comboBox = QtGui.QComboBox(self.verticalLayoutWidget_13)
        self.CNOSSOS_L_eve_1_s_comboBox.setMaximumSize(QtCore.QSize(16777215, 27))
        self.CNOSSOS_L_eve_1_s_comboBox.setObjectName(_fromUtf8("CNOSSOS_L_eve_1_s_comboBox"))
        self.horizontalLayout_23.addWidget(self.CNOSSOS_L_eve_1_s_comboBox)
        self.CNOSSOS_L_nig_1_s_comboBox = QtGui.QComboBox(self.verticalLayoutWidget_13)
        self.CNOSSOS_L_nig_1_s_comboBox.setMaximumSize(QtCore.QSize(16777215, 27))
        self.CNOSSOS_L_nig_1_s_comboBox.setObjectName(_fromUtf8("CNOSSOS_L_nig_1_s_comboBox"))
        self.horizontalLayout_23.addWidget(self.CNOSSOS_L_nig_1_s_comboBox)
        self.verticalLayout_11.addLayout(self.horizontalLayout_23)
        self.CNOSSOS_surface_comboBox = QtGui.QComboBox(self.road_CNOSSOS_page)
        self.CNOSSOS_surface_comboBox.setGeometry(QtCore.QRect(100, 485, 131, 27))
        self.CNOSSOS_surface_comboBox.setObjectName(_fromUtf8("CNOSSOS_surface_comboBox"))
        self.CNOSSOS_slope_comboBox = QtGui.QComboBox(self.road_CNOSSOS_page)
        self.CNOSSOS_slope_comboBox.setGeometry(QtCore.QRect(100, 454, 131, 27))
        self.CNOSSOS_slope_comboBox.setObjectName(_fromUtf8("CNOSSOS_slope_comboBox"))
        self.slope_label_3 = QtGui.QLabel(self.road_CNOSSOS_page)
        self.slope_label_3.setGeometry(QtCore.QRect(20, 457, 71, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slope_label_3.sizePolicy().hasHeightForWidth())
        self.slope_label_3.setSizePolicy(sizePolicy)
        self.slope_label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.slope_label_3.setObjectName(_fromUtf8("slope_label_3"))
        self.surface_label_3 = QtGui.QLabel(self.road_CNOSSOS_page)
        self.surface_label_3.setGeometry(QtCore.QRect(20, 487, 71, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.surface_label_3.sizePolicy().hasHeightForWidth())
        self.surface_label_3.setSizePolicy(sizePolicy)
        self.surface_label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.surface_label_3.setObjectName(_fromUtf8("surface_label_3"))
        self.implementation_label_26 = QtGui.QLabel(self.road_CNOSSOS_page)
        self.implementation_label_26.setGeometry(QtCore.QRect(20, 420, 431, 27))
        self.implementation_label_26.setMaximumSize(QtCore.QSize(16777215, 27))
        self.implementation_label_26.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.implementation_label_26.setObjectName(_fromUtf8("implementation_label_26"))
        self.road_stackedWidget.addWidget(self.road_CNOSSOS_page)
        self.label = QtGui.QLabel(SourceDetailsRoads_window)
        self.label.setGeometry(QtCore.QRect(20, 20, 751, 17))
        self.label.setObjectName(_fromUtf8("label"))

        self.retranslateUi(SourceDetailsRoads_window)
        self.road_stackedWidget.setCurrentIndex(2)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), SourceDetailsRoads_window.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), SourceDetailsRoads_window.reject)
        QtCore.QMetaObject.connectSlotsByName(SourceDetailsRoads_window)

    def retranslateUi(self, SourceDetailsRoads_window):
        SourceDetailsRoads_window.setWindowTitle(_translate("SourceDetailsRoads_window", "Roads Source Details", None))
        self.POWER_R_radioButton.setText(_translate("SourceDetailsRoads_window", "NMPB (power)", None))
        self.NMPB_radioButton.setText(_translate("SourceDetailsRoads_window", "NMPB (traffic flow)", None))
        self.CNOSSOS_radioButton.setText(_translate("SourceDetailsRoads_window", "CNOSSOS", None))
        self.n_l_label_14.setText(_translate("SourceDetailsRoads_window", "Power", None))
        self.POWER_R_L_nig_checkBox.setText(_translate("SourceDetailsRoads_window", "L nig", None))
        self.POWER_R_L_gen_checkBox.setText(_translate("SourceDetailsRoads_window", "Generic", None))
        self.implementation_label_23.setText(_translate("SourceDetailsRoads_window", "Data type", None))
        self.POWER_R_L_eve_checkBox.setText(_translate("SourceDetailsRoads_window", "L eve", None))
        self.POWER_R_L_day_checkBox.setText(_translate("SourceDetailsRoads_window", "L day", None))
        self.NMPB_L_gen_checkBox.setText(_translate("SourceDetailsRoads_window", "Generic", None))
        self.NMPB_L_nig_checkBox.setText(_translate("SourceDetailsRoads_window", "L nig", None))
        self.NMPB_L_eve_checkBox.setText(_translate("SourceDetailsRoads_window", "L eve", None))
        self.NMPB_L_day_checkBox.setText(_translate("SourceDetailsRoads_window", "L day", None))
        self.implementation_label_19.setText(_translate("SourceDetailsRoads_window", "Data type", None))
        self.NMPB_l_checkBox.setText(_translate("SourceDetailsRoads_window", "LIGHT", None))
        self.NMPB_l_n_label.setText(_translate("SourceDetailsRoads_window", "Number / Hour", None))
        self.n_l_label_11.setText(_translate("SourceDetailsRoads_window", "Speed (km/h)", None))
        self.NMPB_h_checkBox.setText(_translate("SourceDetailsRoads_window", "HEAVY", None))
        self.n_l_label_12.setText(_translate("SourceDetailsRoads_window", "Number / Hour", None))
        self.n_l_label_13.setText(_translate("SourceDetailsRoads_window", "Speed (km/h)", None))
        self.implementation_label_21.setText(_translate("SourceDetailsRoads_window", "Vehicle type", None))
        self.implementation_label_25.setText(_translate("SourceDetailsRoads_window", "ALL VEHICLES", None))
        self.type_label.setText(_translate("SourceDetailsRoads_window", "Traffic type", None))
        self.slope_label_4.setText(_translate("SourceDetailsRoads_window", "Slope", None))
        self.surface_label_4.setText(_translate("SourceDetailsRoads_window", "Surface", None))
        self.implementation_label_27.setText(_translate("SourceDetailsRoads_window", "Features not depending from vehicles type or period level:", None))
        self.CNOSSOS_L_nig_checkBox.setText(_translate("SourceDetailsRoads_window", "L nig", None))
        self.CNOSSOS_L_gen_checkBox.setText(_translate("SourceDetailsRoads_window", "Generic", None))
        self.CNOSSOS_L_eve_checkBox.setText(_translate("SourceDetailsRoads_window", "L eve", None))
        self.CNOSSOS_L_day_checkBox.setText(_translate("SourceDetailsRoads_window", "L day", None))
        self.implementation_label_9.setText(_translate("SourceDetailsRoads_window", "Data type", None))
        self.CNOSSOS_2_checkBox.setText(_translate("SourceDetailsRoads_window", "MEDIUM HEAVY", None))
        self.n_l_label_18.setText(_translate("SourceDetailsRoads_window", "Number / Hour", None))
        self.n_l_label_19.setText(_translate("SourceDetailsRoads_window", "Speed (km/h)", None))
        self.CNOSSOS_3_checkBox.setText(_translate("SourceDetailsRoads_window", "HEAVY", None))
        self.n_l_label_20.setText(_translate("SourceDetailsRoads_window", "Number / Hour", None))
        self.n_l_label_21.setText(_translate("SourceDetailsRoads_window", "Speed (km/h)", None))
        self.CNOSSOS_4a_checkBox.setText(_translate("SourceDetailsRoads_window", "2-WHEEL. <= 50cc", None))
        self.n_l_label_22.setText(_translate("SourceDetailsRoads_window", "Number / Hour", None))
        self.n_l_label_23.setText(_translate("SourceDetailsRoads_window", "Speed (km/h)", None))
        self.CNOSSOS_4b_checkBox.setText(_translate("SourceDetailsRoads_window", "2-WHEEL. > 50cc", None))
        self.n_l_label_24.setText(_translate("SourceDetailsRoads_window", "Number / Hour", None))
        self.n_l_label_25.setText(_translate("SourceDetailsRoads_window", "Speed (km/h)", None))
        self.implementation_label_20.setText(_translate("SourceDetailsRoads_window", "Vehicle type", None))
        self.CNOSSOS_1_checkBox.setText(_translate("SourceDetailsRoads_window", "LIGHT", None))
        self.n_l_label_28.setText(_translate("SourceDetailsRoads_window", "Number / Hour", None))
        self.n_l_label_29.setText(_translate("SourceDetailsRoads_window", "Speed (km/h)", None))
        self.slope_label_3.setText(_translate("SourceDetailsRoads_window", "Slope", None))
        self.surface_label_3.setText(_translate("SourceDetailsRoads_window", "Surface", None))
        self.implementation_label_26.setText(_translate("SourceDetailsRoads_window", "Features not depending from vehicles type or period level:", None))
        self.label.setText(_translate("SourceDetailsRoads_window", "For the road sources,  you can set the type of implementation as follow:", None))

